"""GENERATED by scripts/codegen.py from schema.gql. Do not edit.

schema.gql sha256: 29d59267d8bf5a0497b272ac22b5edfb702c4872087b0cffaa1542a81c917834
"""

from enum import StrEnum


class AllowancePeriod(StrEnum):
    'The interval a free allowance resets on and a dimension is rounded over. Every dimension is billed as its period aggregate crosses each whole cent, within about a minute of the usage arriving; the development quota is MONTH.'
    HOUR = 'HOUR'
    DAY = 'DAY'
    MONTH = 'MONTH'


class AppDeploymentTarget(StrEnum):
    'Where an app runs: none (draft), shared (the shared game-api), or dedicated (a provisioned environment).'
    NONE = 'NONE'
    SHARED = 'SHARED'
    DEDICATED = 'DEDICATED'


class AppRuntimeStatus(StrEnum):
    'The per-app runtime gate game-api + Buddy enforce. See runtimeDenialReason when not active.'
    ACTIVE = 'ACTIVE'
    GRACE = 'GRACE'
    DENIED = 'DENIED'
    SUSPENDED = 'SUSPENDED'


class AppStatus(StrEnum):
    'Lifecycle state of an app. Independent of AppVisibility; the public marketplace requires status=LIVE.'
    DRAFT = 'DRAFT'
    LIVE = 'LIVE'
    ARCHIVED = 'ARCHIVED'


class AppVisibility(StrEnum):
    'Controls where an app can be discovered. Independent of AppStatus (the marketplace additionally requires status=LIVE).'
    PUBLIC = 'PUBLIC'
    UNLISTED = 'UNLISTED'
    PRIVATE = 'PRIVATE'


class CheckoutPurpose(StrEnum):
    "Why the checkout exists. Drives which side effect runs on webhook completion: ORG_WALLET_TOPUP credits an org_wallet; PLAYER_WALLET_TOPUP credits the caller's player_wallet; APP_ACCESS_PURCHASE upserts app_user_access; DONATION inserts donations; PROPERTY_TOKENS credits property_tokens; SHARED_APP_SUBSCRIPTION activates a paid shared-environment app slot."
    ORG_WALLET_TOPUP = 'ORG_WALLET_TOPUP'
    PLAYER_WALLET_TOPUP = 'PLAYER_WALLET_TOPUP'
    APP_ACCESS_PURCHASE = 'APP_ACCESS_PURCHASE'
    DONATION = 'DONATION'
    PROPERTY_TOKENS = 'PROPERTY_TOKENS'
    SHARED_APP_SUBSCRIPTION = 'SHARED_APP_SUBSCRIPTION'


class CheckoutStatus(StrEnum):
    'Lifecycle state of a Checkout. Updated by webhook reconciliation, not by the redirect URL.'
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    EXPIRED = 'EXPIRED'
    CANCELED = 'CANCELED'


class CodeAdmissionMode(StrEnum):
    'Controls player-code censorship for an app. IMPLICIT_ALLOW admits lawful code by default; ALLOW_LIST requires every code target, including self-authored code, to match an active code/author/org admission.'
    IMPLICIT_ALLOW = 'IMPLICIT_ALLOW'
    ALLOW_LIST = 'ALLOW_LIST'


class CodeAdmissionSubjectKind(StrEnum):
    'The identity admitted by an app code allow-list entry: one code listing, one author user, or one authoring organization.'
    CODE = 'CODE'
    AUTHOR = 'AUTHOR'
    ORG = 'ORG'


class CrowdyStudioAgentApprovalStatus(StrEnum):
    'Single-use human decision lifecycle for one canonical argument hash.'
    PENDING = 'PENDING'
    GRANTED = 'GRANTED'
    DENIED = 'DENIED'
    CONSUMED = 'CONSUMED'
    REVOKED = 'REVOKED'
    EXPIRED = 'EXPIRED'


class CrowdyStudioAgentEventType(StrEnum):
    'Version 1 durable ordered event vocabulary.'
    SESSION_CREATED = 'SESSION_CREATED'
    SESSION_PAUSED = 'SESSION_PAUSED'
    SESSION_RESUMED = 'SESSION_RESUMED'
    SESSION_CLOSED = 'SESSION_CLOSED'
    CLIENT_ATTACHED = 'CLIENT_ATTACHED'
    CLIENT_DETACHED = 'CLIENT_DETACHED'
    MODE_SELECTED = 'MODE_SELECTED'
    USER_MESSAGE = 'USER_MESSAGE'
    RUN_STARTED = 'RUN_STARTED'
    ASSISTANT_CHUNK = 'ASSISTANT_CHUNK'
    ASSISTANT_MESSAGE = 'ASSISTANT_MESSAGE'
    TOOL_PROPOSED = 'TOOL_PROPOSED'
    TOOL_DISPATCHED = 'TOOL_DISPATCHED'
    TOOL_SUCCEEDED = 'TOOL_SUCCEEDED'
    TOOL_FAILED = 'TOOL_FAILED'
    TOOL_DENIED = 'TOOL_DENIED'
    TOOL_TIMED_OUT = 'TOOL_TIMED_OUT'
    TOOL_OUTCOME_UNKNOWN = 'TOOL_OUTCOME_UNKNOWN'
    APPROVAL_REQUESTED = 'APPROVAL_REQUESTED'
    APPROVAL_GRANTED = 'APPROVAL_GRANTED'
    APPROVAL_DENIED = 'APPROVAL_DENIED'
    APPROVAL_CONSUMED = 'APPROVAL_CONSUMED'
    APPROVAL_EXPIRED = 'APPROVAL_EXPIRED'
    CHECKPOINT_CREATED = 'CHECKPOINT_CREATED'
    CHECKPOINT_RESTORED = 'CHECKPOINT_RESTORED'
    LEASE_GRANTED = 'LEASE_GRANTED'
    LEASE_REVOKED = 'LEASE_REVOKED'
    LEASE_EXPIRED = 'LEASE_EXPIRED'
    CONTEXT_CHANGED = 'CONTEXT_CHANGED'
    BUDGET_UPDATED = 'BUDGET_UPDATED'
    RUN_PAUSED = 'RUN_PAUSED'
    RUN_SUCCEEDED = 'RUN_SUCCEEDED'
    RUN_FAILED = 'RUN_FAILED'
    RUN_CANCELLED = 'RUN_CANCELLED'
    RUN_PREEMPTED = 'RUN_PREEMPTED'


class CrowdyStudioAgentLeaseStatus(StrEnum):
    'Lifecycle of a short-lived workspace or Play capability.'
    ACTIVE = 'ACTIVE'
    REVOKED = 'REVOKED'
    EXPIRED = 'EXPIRED'


class CrowdyStudioAgentLeaseType(StrEnum):
    'Capability family represented by a lease.'
    WORKSPACE = 'WORKSPACE'
    PLAY = 'PLAY'


class CrowdyStudioAgentMode(StrEnum):
    'Human-selected authority mode. The model cannot change modes or elevate itself.'
    ASK = 'ASK'
    BUILD = 'BUILD'
    PLAY = 'PLAY'


class CrowdyStudioAgentPolicyKind(StrEnum):
    'Whether a policy object is the platform row, app row, or intersection.'
    PLATFORM = 'PLATFORM'
    APP = 'APP'
    EFFECTIVE = 'EFFECTIVE'


class CrowdyStudioAgentRiskClass(StrEnum):
    'Tool risk classes from crowdy.agent-tools/1. App policy may only remove platform-allowed classes; locked approval requirements still apply.'
    READ_ONLY = 'READ_ONLY'
    ROUTINE_WRITE = 'ROUTINE_WRITE'
    WORLD_CONTROL = 'WORLD_CONTROL'
    DESTRUCTIVE = 'DESTRUCTIVE'
    TRUST_CONSENT = 'TRUST_CONSENT'
    ECONOMIC = 'ECONOMIC'
    IRREVERSIBLE = 'IRREVERSIBLE'


class CrowdyStudioAgentRunStatus(StrEnum):
    'Serialized durable state of one accepted human message and its provider/tool loop.'
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    WAITING_FOR_TOOL = 'WAITING_FOR_TOOL'
    WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL'
    PAUSED = 'PAUSED'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    PREEMPTED = 'PREEMPTED'


class CrowdyStudioAgentSessionStatus(StrEnum):
    'Durable lifecycle state of an owner/app agent session.'
    ACTIVE = 'ACTIVE'
    PAUSED = 'PAUSED'
    CLOSED = 'CLOSED'
    REVOKED = 'REVOKED'


class CrowdyStudioAgentToolCallStatus(StrEnum):
    'Durable state of one descriptor-pinned serialized tool proposal.'
    PROPOSED = 'PROPOSED'
    WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL'
    DISPATCHED = 'DISPATCHED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    DENIED = 'DENIED'
    TIMED_OUT = 'TIMED_OUT'
    CANCELLED = 'CANCELLED'
    STALE = 'STALE'
    OUTCOME_UNKNOWN = 'OUTCOME_UNKNOWN'


class CrowdyStudioAgentToolExecutor(StrEnum):
    'Trusted boundary that executes a typed tool.'
    SERVER = 'SERVER'
    BROWSER = 'BROWSER'


class CrowdyStudioAgentToolResultStatus(StrEnum):
    'Terminal result reported once by a browser executor.'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    TIMED_OUT = 'TIMED_OUT'
    OUTCOME_UNKNOWN = 'OUTCOME_UNKNOWN'


class CrowdyStudioAgentToolRisk(StrEnum):
    'Server-classified effect risk; app policy may only tighten it.'
    READ_ONLY = 'READ_ONLY'
    ROUTINE_WRITE = 'ROUTINE_WRITE'
    WORLD_CONTROL = 'WORLD_CONTROL'
    DESTRUCTIVE = 'DESTRUCTIVE'
    TRUST_CONSENT = 'TRUST_CONSENT'
    ECONOMIC = 'ECONOMIC'
    IRREVERSIBLE = 'IRREVERSIBLE'


class CrowdyStudioCommonStatus(StrEnum):
    'Crowdy Studio catalog visibility. Player catalog queries return only published entries.'
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    ARCHIVED = 'ARCHIVED'


class CrowdyStudioFileProvenance(StrEnum):
    'How a project file entered the project. Imported content is copied by value; provenance is informational and does not create a live link.'
    AUTHORED = 'AUTHORED'
    LIBRARY = 'LIBRARY'
    COMMON = 'COMMON'


class CrowdyStudioGitHubBindInitial(StrEnum):
    'What the first commit of a bind does. The repository and the Studio project cannot both be the truth on day one, so the owner says which one is.'
    PUSH_PROJECT = 'PUSH_PROJECT'
    TAKE_REPOSITORY = 'TAKE_REPOSITORY'


class CrowdyStudioImportSource(StrEnum):
    'The source catalog used for a copy-by-value project file import.'
    LIBRARY = 'LIBRARY'
    COMMON = 'COMMON'


class CrowdyStudioPairingPreference(StrEnum):
    'Editor preference describing how the project presents its server and client targets; it never grants deployment or runtime authority.'
    PAIRED = 'PAIRED'
    INDEPENDENT = 'INDEPENDENT'
    SERVER_ONLY = 'SERVER_ONLY'
    CLIENT_ONLY = 'CLIENT_ONLY'


class CrowdyStudioProjectSource(StrEnum):
    'Where a project’s files are authored. Every project starts as STUDIO; its owner may bind a GitHub repository later (crowdyStudioGitHubBind) and unbind it again. GitHub is never required.'
    STUDIO = 'STUDIO'
    GITHUB = 'GITHUB'


class CrowdyStudioTarget(StrEnum):
    'The independently capped source target inside a player-owned Crowdy Studio project.'
    SERVER = 'SERVER'
    CLIENT = 'CLIENT'


class DatacenterServingStatus(StrEnum):
    'Whether a datacenter currently has a ck-api instance able to serve clients. Three-valued on purpose: "nothing is serving there" and "the liveness signal could not be read" look identical through a boolean and call for opposite reactions.'
    SERVING = 'SERVING'
    NOT_SERVING = 'NOT_SERVING'
    UNKNOWN = 'UNKNOWN'


class ExecModScope(StrEnum):
    'A rung of the mods kill ladder: one mod (target: its mod id), a player’s mods (their user id), a grid’s mods (its grid id), the installs of a marketplace listing (its listing id), or every mod in the app (no target).'
    MOD = 'MOD'
    PLAYER = 'PLAYER'
    GRID = 'GRID'
    LISTING = 'LISTING'
    ALL = 'ALL'


class GridClaimPolicy(StrEnum):
    'How a player claim confers grid ownership in this app (D4): SELF_CLAIM (the claim alone assigns ownership), APPROVAL (claims create requests designated approvers accept), INVITE (only against a standing invite), or MARKETPLACE_ONLY (direct claims refused). setAppGridClaimPolicy refuses MARKETPLACE_ONLY while paid grid commerce is off the public API.'
    SELF_CLAIM = 'SELF_CLAIM'
    APPROVAL = 'APPROVAL'
    INVITE = 'INVITE'
    MARKETPLACE_ONLY = 'MARKETPLACE_ONLY'


class GridOwnerKind(StrEnum):
    'Kind of principal holding grid title. P1 can assign USER owners; GROUP and ORG are schema-reserved for future shared ownership.'
    USER = 'USER'
    GROUP = 'GROUP'
    ORG = 'ORG'


class GridTenure(StrEnum):
    'Whether the current title is permanent ownership or an expiring rental.'
    OWNED = 'OWNED'
    RENTED = 'RENTED'


class HostedGamePublishState(StrEnum):
    'Lifecycle of one publish. STAGING: upload URLs issued, objects arriving. LIVE: promoted and serving. SUPERSEDED: a later publish went live. FAILED: completion refused. ABANDONED: the developer gave up (abandonGamePublish).'
    STAGING = 'STAGING'
    LIVE = 'LIVE'
    SUPERSEDED = 'SUPERSEDED'
    FAILED = 'FAILED'
    ABANDONED = 'ABANDONED'


class HostedGameStatus(StrEnum):
    'Whether a hosted game is served. LIVE: served at its launchUrl. DISABLED: switched off by its developer (setHostedGameEnabled). TAKEN_DOWN: removed by an operator; the developer cannot publish or re-enable until an operator restores it.'
    LIVE = 'LIVE'
    DISABLED = 'DISABLED'
    TAKEN_DOWN = 'TAKEN_DOWN'


class PaymentProvider(StrEnum):
    'External payment processor for a checkout.'
    STRIPE = 'STRIPE'
    PAYPAL = 'PAYPAL'


class PlayerCodeAcquisitionMode(StrEnum):
    'How a listing is acquired. P4a ships FREE only; the paid modes (buy, rent, time-limited, cost-limited) arrive with the P4b money workstream.'
    FREE = 'FREE'
    BUY = 'BUY'
    RENT = 'RENT'
    TIME_LIMITED = 'TIME_LIMITED'
    COST_LIMITED = 'COST_LIMITED'


class PlayerCodeAdmissionState(StrEnum):
    "A listing's standing under this app's admission mode: ADMITTED (installable), PENDING (browsable but uninstallable in allow_list apps), or REVOKED (installs drain)."
    ADMITTED = 'ADMITTED'
    PENDING = 'PENDING'
    REVOKED = 'REVOKED'


class PlayerCodeLicenseMode(StrEnum):
    'Source-access mode of a listing: CLOSED (artifacts + contracts only) or OPEN_SOURCE (source readable; irreversible per published version).'
    CLOSED = 'CLOSED'
    OPEN_SOURCE = 'OPEN_SOURCE'


class PlayerCodeListingStatus(StrEnum):
    'Catalog status of a listing: ACTIVE (browsable/acquirable), DELISTED (author withdrew it — existing installs keep their pinned versions), KILLED (studio/operator kill).'
    ACTIVE = 'ACTIVE'
    DELISTED = 'DELISTED'
    KILLED = 'KILLED'


class PlayerCodeOwnerKind(StrEnum):
    'Who owns a marketplace code listing: a player user or an org (DN-9: the org then holds source access and listing control).'
    USER = 'USER'
    ORG = 'ORG'


class RateScope(StrEnum):
    'Which rate card. SHARED prices organization metered usage for shared-environment apps (billed hourly to the org wallet as "shared_usage"). PLAYER prices player compute (billed hourly to the player wallet as "usage_debit").'
    SHARED = 'SHARED'
    PLAYER = 'PLAYER'


class ServerState(StrEnum):
    'Lifecycle/capacity state of a game/GraphQL server in the fleet. Only ReadyForClients servers should receive new client connections; serverWithLeastClients and activeGraphQLServers already filter to healthy, non-overloaded servers.'
    Starting = 'Starting'
    ReadyForClients = 'ReadyForClients'
    Stopping = 'Stopping'
    Offline = 'Offline'
    NearCapacity = 'NearCapacity'
    Full = 'Full'


class UdpErrorCode(StrEnum):
    'Error codes returned by UDP game servers (and surfaced on `GenericErrorResponse.errorCode`) in response to a spatial/realtime message. NO_ERROR (0) indicates success; every other value indicates a failure. The numeric value is the byte sent on the wire; GraphQL exposes the name. Note: a failed message does not always produce an error — some auth failures are dropped silently (see the docs).'
    NO_ERROR = 'NO_ERROR'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND'
    BAD_PASSWORD = 'BAD_PASSWORD'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
    INVALID_TOKEN = 'INVALID_TOKEN'
    APP_NOT_FOUND = 'APP_NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'
    APP_NOT_LOADED = 'APP_NOT_LOADED'
    EMAIL_TOO_SHORT = 'EMAIL_TOO_SHORT'
    EMAIL_TOO_LONG = 'EMAIL_TOO_LONG'
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT'
    PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG'
    GAME_TOKEN_WRONG_SIZE = 'GAME_TOKEN_WRONG_SIZE'
    NAME_TOO_LONG = 'NAME_TOO_LONG'
    INVALID_REQUEST = 'INVALID_REQUEST'
    EMAIL_INVALID = 'EMAIL_INVALID'
    INVALID_TOKEN_LENGTH = 'INVALID_TOKEN_LENGTH'
    INVALID_APP_ID = 'INVALID_APP_ID'
    CHUNK_NOT_FOUND = 'CHUNK_NOT_FOUND'
    USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED'
    INVALID_STATE_DATA = 'INVALID_STATE_DATA'
    USER_NOT_APP_ADMIN = 'USER_NOT_APP_ADMIN'
    GRID_OUTSIDE_ASSIGNMENT = 'GRID_OUTSIDE_ASSIGNMENT'
    NO_MATCHING_GRID_ASSIGNMENT = 'NO_MATCHING_GRID_ASSIGNMENT'
    INVALID_GRID_COORDINATES = 'INVALID_GRID_COORDINATES'
    GRID_ALREADY_EXISTS = 'GRID_ALREADY_EXISTS'
    GRID_OVERLAPS_EXISTING = 'GRID_OVERLAPS_EXISTING'
    GAMERTAG_ALREADY_EXISTS = 'GAMERTAG_ALREADY_EXISTS'
    GRID_NOT_FOUND = 'GRID_NOT_FOUND'
    CANNOT_DELETE_DEFAULT_WORLD_GRID = 'CANNOT_DELETE_DEFAULT_WORLD_GRID'
    GRID_HAS_NESTED_CHILDREN = 'GRID_HAS_NESTED_CHILDREN'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'


__all__ = [
    'AllowancePeriod',
    'AppDeploymentTarget',
    'AppRuntimeStatus',
    'AppStatus',
    'AppVisibility',
    'CheckoutPurpose',
    'CheckoutStatus',
    'CodeAdmissionMode',
    'CodeAdmissionSubjectKind',
    'CrowdyStudioAgentApprovalStatus',
    'CrowdyStudioAgentEventType',
    'CrowdyStudioAgentLeaseStatus',
    'CrowdyStudioAgentLeaseType',
    'CrowdyStudioAgentMode',
    'CrowdyStudioAgentPolicyKind',
    'CrowdyStudioAgentRiskClass',
    'CrowdyStudioAgentRunStatus',
    'CrowdyStudioAgentSessionStatus',
    'CrowdyStudioAgentToolCallStatus',
    'CrowdyStudioAgentToolExecutor',
    'CrowdyStudioAgentToolResultStatus',
    'CrowdyStudioAgentToolRisk',
    'CrowdyStudioCommonStatus',
    'CrowdyStudioFileProvenance',
    'CrowdyStudioGitHubBindInitial',
    'CrowdyStudioImportSource',
    'CrowdyStudioPairingPreference',
    'CrowdyStudioProjectSource',
    'CrowdyStudioTarget',
    'DatacenterServingStatus',
    'ExecModScope',
    'GridClaimPolicy',
    'GridOwnerKind',
    'GridTenure',
    'HostedGamePublishState',
    'HostedGameStatus',
    'PaymentProvider',
    'PlayerCodeAcquisitionMode',
    'PlayerCodeAdmissionState',
    'PlayerCodeLicenseMode',
    'PlayerCodeListingStatus',
    'PlayerCodeOwnerKind',
    'RateScope',
    'ServerState',
    'UdpErrorCode',
]
