"""GENERATED by scripts/codegen.py from schema.gql. Do not edit.

Every GraphQL input object as a msgspec Struct. Attributes are snake_case and encode
under their GraphQL names; an attribute left at UNSET is omitted from the request,
which is how the API tells 'not provided' from an explicit null.

schema.gql sha256: 5dcaf15c772c89fe250ecdbd83eb21b52b67f27d739fca38c2871b5553751ab0
"""

from __future__ import annotations

from typing import Any

import msgspec
from msgspec import UNSET, UnsetType

from crowdypy._generated.enums import AllowancePeriod, AppDeploymentTarget, AppRuntimeStatus, AppStatus, AppVisibility, CheckoutPurpose, CheckoutStatus, CodeAdmissionMode, CodeAdmissionSubjectKind, CrowdyStudioAgentApprovalStatus, CrowdyStudioAgentEventType, CrowdyStudioAgentLeaseStatus, CrowdyStudioAgentLeaseType, CrowdyStudioAgentMode, CrowdyStudioAgentPolicyKind, CrowdyStudioAgentRiskClass, CrowdyStudioAgentRunStatus, CrowdyStudioAgentSessionStatus, CrowdyStudioAgentToolCallStatus, CrowdyStudioAgentToolExecutor, CrowdyStudioAgentToolResultStatus, CrowdyStudioAgentToolRisk, CrowdyStudioCommonStatus, CrowdyStudioFileProvenance, CrowdyStudioGitHubBindInitial, CrowdyStudioImportSource, CrowdyStudioPairingPreference, CrowdyStudioProjectSource, CrowdyStudioTarget, DatacenterServingStatus, ExecModScope, GridClaimPolicy, GridOwnerKind, GridTenure, HostedGamePublishState, HostedGameStatus, PaymentProvider, PlayerCodeAcquisitionMode, PlayerCodeAdmissionState, PlayerCodeLicenseMode, PlayerCodeListingStatus, PlayerCodeOwnerKind, RateScope, ServerState, UdpErrorCode


class ActorFilterInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'avatar_id': 'avatarId'}):
    app_id: str | None | UnsetType = UNSET
    avatar_id: str | None | UnsetType = UNSET
    uuid: str | None | UnsetType = UNSET
    chunk: ChunkCoordinatesInput | None | UnsetType = UNSET


class ActorUpdateRequestInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending an actor update request to the UDP game server. This updates the state of an actor (player character or NPC) in a specific chunk.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    state: str
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


class AdmitAppCodeInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'subject_kind': 'subjectKind', 'subject_ref': 'subjectRef', 'version_range': 'versionRange'}):
    app_id: str
    subject_kind: CodeAdmissionSubjectKind
    subject_ref: str
    version_range: str | None | UnsetType = UNSET


class AppMarketplaceFilterInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_slug': 'orgSlug'}):
    'Optional filters for the public marketplace apps listing.'
    query: str | None | UnsetType = UNSET
    org_slug: str | None | UnsetType = UNSET


class AssignGridOwnershipInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'owner_user_id': 'ownerUserId', 'expires_at': 'expiresAt'}):
    app_id: str
    grid_id: str
    owner_user_id: str
    tenure: GridTenure | None | UnsetType = UNSET
    expires_at: str | None | UnsetType = UNSET


class AssignGroupToGridInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'group_id': 'groupId', 'group_role_id': 'groupRoleId', 'permission_keys': 'permissionKeys', 'expires_at': 'expiresAt'}):
    'Grant runtime permission keys to a group (optionally one role) on a grid (writes the grid_group_grants input table).'
    app_id: str
    grid_id: str
    group_id: str
    group_role_id: str | None | UnsetType = UNSET
    permission_keys: list[str]
    expires_at: str | None | UnsetType = UNSET


class AuthorizeAppInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Approve (consent to) an app receiving app-scoped tokens via the Overworld portal.'
    app_id: str
    scopes: list[str] | None | UnsetType = UNSET


class BatchActorLookupInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    uuids: list[str]


class BeginGamePublishInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Declare a publish: every file of the built bundle.'
    slug: str
    files: list[PublishFileInput]


class BindCrowdyStudioGitHubInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId'}):
    app_id: str
    project_id: str
    owner: str
    repo: str
    branch: str | None | UnsetType = UNSET
    initial: CrowdyStudioGitHubBindInitial


class ChannelMessageInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'channel_id': 'channelId', 'sequence_number': 'sequenceNumber'}):
    'Input for publishing a message to a channel. Delivered to every active member of the channel (regardless of location), not chunk-routed. The sender must have the channel send_messages permission.'
    channel_id: str
    uuid: str
    payload: str
    sequence_number: int | None | UnsetType = UNSET


class CheckAuthMethodInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Check whether an account has password sign-in enabled (email-first adaptive login).'
    email: str


class CheckoutFilterInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'user_id': 'userId', 'org_id': 'orgId', 'app_id': 'appId'}):
    provider: PaymentProvider | None | UnsetType = UNSET
    purpose: CheckoutPurpose | None | UnsetType = UNSET
    status: CheckoutStatus | None | UnsetType = UNSET
    user_id: str | None | UnsetType = UNSET
    org_id: str | None | UnsetType = UNSET
    app_id: str | None | UnsetType = UNSET


class ChunkCoordinatesInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Input form of a chunk address (see ChunkCoordinates). Each component is a signed 64-bit integer passed as a decimal string (see the BigInt scalar); all three are required.'
    x: str
    y: str
    z: str


class ChunkUpdateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'voxel_states': 'voxelStates'}):
    "Payload for updateChunk: upserts a chunk's dense voxel grid and/or per-voxel states and logs each provided state as an individual voxel update. Does NOT modify chunkState or LODs."
    app_id: str
    coordinates: ChunkCoordinatesInput
    voxels: str | None | UnsetType = UNSET
    voxel_states: list[VoxelStateInput] | None | UnsetType = UNSET


class ClaimGameHostingInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Claim (or re-assert) the hosting slug for an app.'
    app_id: str
    slug: str | None | UnsetType = UNSET


class ClientAudioPacketInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'audio_data': 'audioData', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending a client audio packet (voice chat) to the UDP game server. The audio data is compressed and will be broadcast to nearby players.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    audio_data: str
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


class ClientEventNotificationInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'event_type': 'eventType', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending a client event notification to the UDP game server. Events are custom game events that can be used for various gameplay mechanics. The event type and state format are defined by the client/mod.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    event_type: int
    state: str
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


class ClientTextPacketInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending a text message (chat) to the UDP game server. The text will be broadcast to nearby players in the same chunk.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    text: str
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


class ClientVideoPacketInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'video_data': 'videoData', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending one webcam video FRAGMENT to the UDP game server, fanned out to nearby players as a ClientVideoNotification. A datagram carries at most ~1117 bytes of videoData, so an encoded frame is split by the SDK into fragments that each start with the 6-byte video fragment header (version, codec, frameId, fragIndex, fragCount) and are reassembled by the receiver; this mutation sends ONE such fragment. Sustained video belongs on the binary realtime relay; this path works but is a mutation per fragment.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    video_data: str
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


class CompleteLoginLinkInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Complete a magic-link sign-in with the emailed token.'
    token: str


class CreateAccessTierInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'tier_order': 'tierOrder', 'is_free': 'isFree', 'is_default': 'isDefault', 'permission_keys': 'permissionKeys'}):
    'Input for creating a new app access tier.'
    app_id: str
    name: str
    tier_order: int | None | UnsetType = UNSET
    is_free: bool | None | UnsetType = UNSET
    is_default: bool | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    permission_keys: list[str] | None | UnsetType = UNSET


class CreateActorInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'avatar_id': 'avatarId', 'private_state': 'privateState', 'public_state': 'publicState'}):
    app_id: str
    avatar_id: str | None | UnsetType = UNSET
    uuid: str
    chunk: ChunkCoordinatesInput
    private_state: str | None | UnsetType = UNSET
    public_state: str | None | UnsetType = UNSET


class CreateAppInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId'}):
    'Input payload for creating a new app.'
    org_id: str
    name: str
    slug: str
    datacenter: str
    description: str | None | UnsetType = UNSET
    visibility: AppVisibility | None | UnsetType = UNSET
    status: AppStatus | None | UnsetType = UNSET
    metadata: str | None | UnsetType = UNSET


class CreateAvatarInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    name: str | None | UnsetType = UNSET


class CreateChannelInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'membership_policy': 'membershipPolicy', 'members_can_send': 'membersCanSend'}):
    'Create a channel in an app.'
    app_id: str
    name: str
    description: str | None | UnsetType = UNSET
    membership_policy: str | None | UnsetType = UNSET
    members_can_send: bool | None | UnsetType = UNSET


class CreateCheckoutInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'app_id': 'appId', 'tier_id': 'tierId', 'plan_id': 'planId', 'amount_cents': 'amountCents', 'success_url': 'successUrl', 'cancel_url': 'cancelUrl', 'idempotency_key': 'idempotencyKey'}):
    provider: PaymentProvider
    purpose: CheckoutPurpose
    org_id: str | None | UnsetType = UNSET
    app_id: str | None | UnsetType = UNSET
    tier_id: str | None | UnsetType = UNSET
    plan_id: str | None | UnsetType = UNSET
    amount_cents: str | None | UnsetType = UNSET
    currency: str | None | UnsetType = UNSET
    success_url: str | None | UnsetType = UNSET
    cancel_url: str | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class CreateCrowdyStudioProjectInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'server_module_name': 'serverModuleName', 'client_module_name': 'clientModuleName', 'pairing_preference': 'pairingPreference', 'sdk_version': 'sdkVersion', 'abi_version': 'abiVersion', 'initial_files': 'initialFiles', 'idempotency_key': 'idempotencyKey'}):
    'Create a private player-owned project, optionally with bounded initial files for either target.'
    app_id: str
    grid_id: str | None | UnsetType = UNSET
    name: str
    description: str | None | UnsetType = UNSET
    server_module_name: str | None | UnsetType = UNSET
    client_module_name: str | None | UnsetType = UNSET
    pairing_preference: CrowdyStudioPairingPreference | None | UnsetType = UNSET
    sdk_version: str | None | UnsetType = UNSET
    abi_version: int | None | UnsetType = UNSET
    initial_files: list[CrowdyStudioProjectFileInput] | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class CreateGridChannelInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'membership_policy': 'membershipPolicy', 'members_can_send': 'membersCanSend', 'grid_id': 'gridId'}):
    "Create a grid channel (DN-10): a channel that belongs to one grid, so that grid's player modules may emit_channel into it. Only the grid's current owner may create one."
    app_id: str
    name: str
    description: str | None | UnsetType = UNSET
    membership_policy: str | None | UnsetType = UNSET
    members_can_send: bool | None | UnsetType = UNSET
    grid_id: str


class CreateGridInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Defines a new grid by its app and two opposite corner chunks. The corners are normalized server-side into a low/high chunk box, so corner order is irrelevant and a single chunk (corner1 == corner2) is allowed.'
    app_id: str
    corner1: ChunkCoordinatesInput
    corner2: ChunkCoordinatesInput


class CreateGroupRoleInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'group_id': 'groupId', 'role_name': 'roleName'}):
    'Create a custom role within a group (team or channel), granting group permission keys.'
    group_id: str
    role_name: str
    permissions: list[str] | None | UnsetType = UNSET
    rank: int | None | UnsetType = UNSET


class CreateOrgRoleInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'role_name': 'roleName'}):
    org_id: str
    role_name: str
    description: str | None | UnsetType = UNSET
    permissions: list[str]


class CreateOrgTokenInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'expires_at': 'expiresAt'}):
    org_id: str
    label: str | None | UnsetType = UNSET
    expires_at: str | None | UnsetType = UNSET


class CreateOrganizationInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    name: str
    slug: str


class CreatePortalAuthorizationCodeInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'code_challenge': 'codeChallenge', 'code_challenge_method': 'codeChallengeMethod', 'redirect_uri': 'redirectUri'}):
    'Input for createPortalAuthorizationCode: the Overworld (identity origin, holding the session token) mints a one-time code the destination game exchanges for an app token. Browser handoff path; pair with a PKCE verifier held by the destination game origin.'
    app_id: str
    code_challenge: str
    code_challenge_method: str | None | UnsetType = UNSET
    redirect_uri: str


class CreateTeamInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'membership_policy': 'membershipPolicy'}):
    'Create a team in an app.'
    app_id: str
    name: str
    description: str | None | UnsetType = UNSET
    membership_policy: str | None | UnsetType = UNSET


class CreateUserAppStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    app_id: str
    state: str | None | UnsetType = UNSET


class CrowdyStudioAgentFundingPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'billing_mode': 'billingMode', 'payer_kind': 'payerKind', 'wallet_debit_enabled': 'walletDebitEnabled'}):
    "Funding patch. On the platform layer: billingMode ('PLATFORM_FUNDED' | 'METERED') and walletDebitEnabled. On an app layer: payerKind ('PLAYER' | 'ORG'); choosing ORG spends the org wallet and requires manage_billing on the org. Omitted fields stay unchanged."
    billing_mode: str | None | UnsetType = UNSET
    payer_kind: str | None | UnsetType = UNSET
    wallet_debit_enabled: bool | None | UnsetType = UNSET


class CrowdyStudioAgentPlayerDayLimitsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'provider_requests': 'providerRequests', 'input_tokens': 'inputTokens', 'output_tokens': 'outputTokens', 'reasoning_tokens': 'reasoningTokens', 'total_tokens': 'totalTokens', 'provider_cost_microusd': 'providerCostMicrousd', 'tool_calls': 'toolCalls', 'concurrent_sessions': 'concurrentSessions', 'concurrent_runs_per_app': 'concurrentRunsPerApp'}):
    'Patch for per-player/day and app concurrency limits. Omitted values stay unchanged; supplied values are clamped down to platform ceilings.'
    provider_requests: int | None | UnsetType = UNSET
    input_tokens: str | None | UnsetType = UNSET
    output_tokens: str | None | UnsetType = UNSET
    reasoning_tokens: str | None | UnsetType = UNSET
    total_tokens: str | None | UnsetType = UNSET
    provider_cost_microusd: str | None | UnsetType = UNSET
    tool_calls: int | None | UnsetType = UNSET
    compiles: int | None | UnsetType = UNSET
    concurrent_sessions: int | None | UnsetType = UNSET
    concurrent_runs_per_app: int | None | UnsetType = UNSET


class CrowdyStudioAgentPrivacyPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'allow_private_source': 'allowPrivateSource'}):
    'App/platform privacy patch. It can disable private-source sharing; ZDR, collection denial, first-use consent, and provider-body non-persistence are locked.'
    allow_private_source: bool | None | UnsetType = UNSET


class CrowdyStudioAgentRetentionPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'assistant_chunk_hours': 'assistantChunkHours', 'detailed_context_hours': 'detailedContextHours', 'session_data_days': 'sessionDataDays', 'usage_days': 'usageDays'}):
    'Retention patch. Values may only shorten the platform policy and the hard pilot maxima.'
    assistant_chunk_hours: int | None | UnsetType = UNSET
    detailed_context_hours: int | None | UnsetType = UNSET
    session_data_days: int | None | UnsetType = UNSET
    usage_days: int | None | UnsetType = UNSET


class CrowdyStudioAgentSessionLimitsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'provider_requests': 'providerRequests', 'input_tokens': 'inputTokens', 'output_tokens': 'outputTokens', 'reasoning_tokens': 'reasoningTokens', 'total_tokens': 'totalTokens', 'provider_cost_microusd': 'providerCostMicrousd', 'tool_calls': 'toolCalls', 'concurrent_runs': 'concurrentRuns'}):
    'Patch for per-session limits. Omitted values stay unchanged; supplied values are clamped down to platform ceilings.'
    provider_requests: int | None | UnsetType = UNSET
    input_tokens: str | None | UnsetType = UNSET
    output_tokens: str | None | UnsetType = UNSET
    reasoning_tokens: str | None | UnsetType = UNSET
    total_tokens: str | None | UnsetType = UNSET
    provider_cost_microusd: str | None | UnsetType = UNSET
    tool_calls: int | None | UnsetType = UNSET
    compiles: int | None | UnsetType = UNSET
    concurrent_runs: int | None | UnsetType = UNSET


class CrowdyStudioAgentTurnLimitsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'provider_requests': 'providerRequests', 'input_tokens': 'inputTokens', 'output_tokens': 'outputTokens', 'reasoning_tokens': 'reasoningTokens', 'total_tokens': 'totalTokens', 'provider_cost_microusd': 'providerCostMicrousd', 'tool_calls': 'toolCalls', 'tool_rounds': 'toolRounds', 'wall_clock_ms': 'wallClockMs', 'concurrent_provider_requests': 'concurrentProviderRequests'}):
    'Patch for per-turn limits. Omitted values stay unchanged; supplied values must be positive and are clamped down to platform ceilings.'
    provider_requests: int | None | UnsetType = UNSET
    input_tokens: str | None | UnsetType = UNSET
    output_tokens: str | None | UnsetType = UNSET
    reasoning_tokens: str | None | UnsetType = UNSET
    total_tokens: str | None | UnsetType = UNSET
    provider_cost_microusd: str | None | UnsetType = UNSET
    tool_calls: int | None | UnsetType = UNSET
    tool_rounds: int | None | UnsetType = UNSET
    compiles: int | None | UnsetType = UNSET
    wall_clock_ms: int | None | UnsetType = UNSET
    concurrent_provider_requests: int | None | UnsetType = UNSET


class CrowdyStudioGitHubAtCommitInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'commit_sha': 'commitSha'}):
    app_id: str
    project_id: str
    commit_sha: str | None | UnsetType = UNSET


class CrowdyStudioGitHubDeleteFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_commit_sha': 'expectedCommitSha'}):
    app_id: str
    project_id: str
    path: str
    message: str
    sha: str | None | UnsetType = UNSET
    expected_commit_sha: str


class CrowdyStudioGitHubFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'commit_sha': 'commitSha'}):
    app_id: str
    project_id: str
    commit_sha: str | None | UnsetType = UNSET
    path: str


class CrowdyStudioGitHubProjectInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId'}):
    app_id: str
    project_id: str


class CrowdyStudioGitHubPutFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_commit_sha': 'expectedCommitSha'}):
    app_id: str
    project_id: str
    path: str
    content: str
    message: str
    sha: str | None | UnsetType = UNSET
    expected_commit_sha: str


class CrowdyStudioProjectFileDeleteInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'A target/path key removed atomically by crowdyStudioProjectSaveFiles.'
    target: CrowdyStudioTarget
    path: str


class CrowdyStudioProjectFileInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'One direct-authored initial or batch-upsert project file. Paths and UTF-8 bytes are validated against player-compute safety limits.'
    target: CrowdyStudioTarget
    path: str
    content: str


class CurrentServerInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'client_port': 'clientPort'}):
    'The Buddy a native client is CURRENTLY connected to, named by the `ip4` and `clientPort` that `serverWithLeastClients` handed it. Pass it to `refreshAppToken` so the refreshed token is authorized on that same node and the client keeps its session there instead of being re-placed.'
    ip4: str
    client_port: int


class DefineAppFeatureInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'feature_key': 'featureKey'}):
    'Define an app feature key.'
    app_id: str
    feature_key: str
    description: str | None | UnsetType = UNSET


class DeleteGridInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId'}):
    'Identifies a studio-created grid to delete. The default open-by-default world grid and grids that still contain nested child grids cannot be removed.'
    app_id: str
    grid_id: str


class ExchangePortalCodeInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'code_verifier': 'codeVerifier'}):
    'Input for exchangePortalCode: the destination game (public client) trades a one-time portal code for an app-scoped gameplay token. Public (the code + PKCE verifier authorize the call).'
    code: str
    code_verifier: str | None | UnsetType = UNSET


class ExecArtifactInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'wasm_base64': 'wasmBase64'}):
    'One compiled module for a ck-exec deploy.'
    digest: str
    wasm_base64: str


class ExecBuildCrateInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'One crate of a ck-exec build: a `ckx-sdk` library with `[lib] crate-type = ["cdylib"]`, built into one module.'
    name: str
    files: list[ExecBuildFileInput]


class ExecBuildFileInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'One source file of a ck-exec crate.'
    path: str
    content: str


class ExecBuildInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Sources to build into ck-exec modules.'
    app_id: str
    crates: list[ExecBuildCrateInput]


class ExecDeployInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'manifest_json': 'manifestJson', 'build_id': 'buildId'}):
    'A new version of an app’s ck-exec topology.'
    app_id: str
    manifest_json: str
    artifacts: list[ExecArtifactInput] | None | UnsetType = UNSET
    build_id: str | None | UnsetType = UNSET


class GetChunkInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'requested_lod_levels': 'requestedLodLevels', 'include_all_lods': 'includeAllLods'}):
    'Arguments for getChunk: selects a single chunk by app id and chunk coordinates, with optional LOD filtering.'
    app_id: str
    coordinates: ChunkCoordinatesInput
    requested_lod_levels: list[int] | None | UnsetType = UNSET
    include_all_lods: bool | None | UnsetType = UNSET


class GetChunkLodsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'lod_levels': 'lodLevels'}):
    'Arguments for getChunkLods: selects the LOD meshes for one chunk and returns only the requested levels.'
    app_id: str
    coordinates: ChunkCoordinatesInput
    lod_levels: list[int]


class GetChunksByDistanceInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'center_coordinate': 'centerCoordinate', 'max_distance': 'maxDistance'}):
    'Arguments for getChunksByDistance: selects chunks within a cubic (Chebyshev-distance) radius around a center chunk, with pagination.'
    app_id: str
    center_coordinate: ChunkCoordinatesInput
    max_distance: int
    limit: int | None | UnsetType = UNSET
    skip: int | None | UnsetType = UNSET


class GetVoxelListInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Arguments for getVoxelList: selects all recorded voxel edits for one chunk by app id and chunk coordinates.'
    app_id: str
    coordinates: ChunkCoordinatesInput


class GrantAppAccessInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'user_id': 'userId', 'tier_id': 'tierId', 'granted_by': 'grantedBy', 'idempotency_key': 'idempotencyKey'}):
    'Input for granting a user access to an app, optionally on a specific tier.'
    app_id: str
    user_id: str
    tier_id: str | None | UnsetType = UNSET
    granted_by: str | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class GrantGridPermissionsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'user_id': 'userId', 'permission_keys': 'permissionKeys', 'expires_at': 'expiresAt'}):
    'Grant runtime permission keys directly to one user on one grid (writes the grid_user_direct_grants input table).'
    app_id: str
    grid_id: str
    user_id: str
    permission_keys: list[str]
    expires_at: str | None | UnsetType = UNSET


class GrantTierFeatureInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'tier_id': 'tierId', 'feature_key': 'featureKey'}):
    'Grant or revoke a feature key for an access tier.'
    app_id: str
    tier_id: str
    feature_key: str


class ImportCrowdyStudioProjectFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_project_revision': 'expectedProjectRevision', 'library_file_id': 'libraryFileId', 'common_version_id': 'commonVersionId', 'destination_path': 'destinationPath', 'idempotency_key': 'idempotencyKey'}):
    'Copy a private library revision or immutable published common version into a project by value.'
    app_id: str
    project_id: str
    expected_project_revision: str
    source: CrowdyStudioImportSource
    library_file_id: str | None | UnsetType = UNSET
    common_version_id: str | None | UnsetType = UNSET
    destination_path: str | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class InviteOrgMemberInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'user_id': 'userId'}):
    org_id: str
    user_id: str


class LinkIdentityInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Link an additional federated identity to the signed-in account.'
    provider: str
    code: str
    state: str


class ListVoxelUpdatesByDistanceInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'center_coordinate': 'centerCoordinate', 'max_distance': 'maxDistance'}):
    'Arguments for listVoxelUpdatesByDistance: selects recorded voxel edits across chunks within a cubic (Chebyshev) radius of a center chunk, grouped per chunk and ordered by increasing distance.'
    app_id: str
    center_coordinate: ChunkCoordinatesInput
    max_distance: int
    limit: int | None | UnsetType = UNSET
    skip: int | None | UnsetType = UNSET
    since: str | None | UnsetType = UNSET


class ListVoxelsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Arguments for listVoxels: selects recorded voxel edits for one chunk, optionally only those at/after a timestamp.'
    app_id: str
    coordinates: ChunkCoordinatesInput
    since: str | None | UnsetType = UNSET


class LodDataInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'A single LOD level and its encoded data for a chunk.'
    level: int
    data: str


class LoginUserInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    email: str
    password: str


class MintAppTokenInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Input for mintAppToken: directly mint an app-scoped gameplay token for the calling user (native/direct path, no browser redirect).'
    app_id: str


class MintGridTokenInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'ttl_seconds': 'ttlSeconds'}):
    'Narrow the app token you hold to one grid (DN-10 grid-scoped token).'
    app_id: str
    grid_id: str
    ttl_seconds: int | None | UnsetType = UNSET


class NearbyGridPermissionsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'user_id': 'userId', 'low_chunk': 'lowChunk', 'high_chunk': 'highChunk'}):
    "Scan a region for grids and report a user's effective permissions on each."
    app_id: str
    user_id: str
    low_chunk: ChunkCoordinatesInput
    high_chunk: ChunkCoordinatesInput


class NearbyGridsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'low_chunk': 'lowChunk', 'high_chunk': 'highChunk'}):
    'Scan a region for grids. Player-safe: returns bounds only, no permission keys and no impersonation userId.'
    app_id: str
    low_chunk: ChunkCoordinatesInput
    high_chunk: ChunkCoordinatesInput


class PublishCrowdyStudioCommonFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'common_file_id': 'commonFileId', 'idempotency_key': 'idempotencyKey'}):
    'Publish a new immutable Crowdy Studio-curated common-file version. Requires the app manage_compute permission.'
    app_id: str
    common_file_id: str | None | UnsetType = UNSET
    slug: str
    title: str
    description: str | None | UnsetType = UNSET
    path: str
    target: CrowdyStudioTarget
    tags: list[str] | None | UnsetType = UNSET
    content: str
    idempotency_key: str | None | UnsetType = UNSET


class PublishFileInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'One file of a publish manifest.'
    path: str
    size: int
    sha256: str


class RegisterUserInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    email: str
    password: str
    gamertag: str | None | UnsetType = UNSET


class ReinstateOrganizationInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId'}):
    'Which retired organization to put back, and why.'
    org_id: str
    reason: str


class RequestLoginLinkInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'redirect_uri': 'redirectUri'}):
    'Request an emailed magic-link to sign in (passwordless).'
    email: str
    redirect_uri: str | None | UnsetType = UNSET


class ResetPasswordInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'new_password': 'newPassword'}):
    token: str
    new_password: str


class RetireOrganizationInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'expected_slug': 'expectedSlug', 'acknowledge_frozen_balance': 'acknowledgeFrozenBalance', 'acknowledge_probe_infrastructure': 'acknowledgeProbeInfrastructure'}):
    'Which organization to retire, proof that you mean that one, and why.'
    org_id: str
    expected_slug: str
    reason: str
    acknowledge_frozen_balance: bool | None | UnsetType = UNSET
    acknowledge_probe_infrastructure: bool | None | UnsetType = UNSET


class RevokeGridPermissionsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'user_id': 'userId', 'permission_keys': 'permissionKeys', 'idempotency_key': 'idempotencyKey'}):
    "Revoke a user's direct grants on a grid (deletes from the grid_user_direct_grants input table)."
    app_id: str
    grid_id: str
    user_id: str
    permission_keys: list[str] | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class RevokeGroupFromGridInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'group_id': 'groupId', 'group_role_id': 'groupRoleId', 'permission_keys': 'permissionKeys'}):
    "Revoke a group's (optionally one role's) grants on a grid (deletes from the grid_group_grants input table)."
    app_id: str
    grid_id: str
    group_id: str
    group_role_id: str | None | UnsetType = UNSET
    permission_keys: list[str] | None | UnsetType = UNSET


class RollbackVoxelUpdatesInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'user_id': 'userId', 'from_': 'from', 'dry_run': 'dryRun', 'idempotency_key': 'idempotencyKey'}):
    'Payload for rollbackVoxelUpdates: selects the voxel edits made by one user in one app within a time window to revert.'
    app_id: str
    user_id: str
    from_: str
    to: str
    dry_run: bool
    idempotency_key: str | None | UnsetType = UNSET


class SaveCrowdyStudioLibraryFileInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'library_file_id': 'libraryFileId', 'expected_revision': 'expectedRevision', 'path_hint': 'pathHint', 'idempotency_key': 'idempotencyKey'}):
    'Create or optimistically update one private reusable personal-library file.'
    app_id: str
    library_file_id: str | None | UnsetType = UNSET
    expected_revision: str | None | UnsetType = UNSET
    title: str
    path_hint: str
    target: CrowdyStudioTarget
    tags: list[str] | None | UnsetType = UNSET
    content: str
    idempotency_key: str | None | UnsetType = UNSET


class SaveCrowdyStudioProjectFilesInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_revision': 'expectedRevision', 'idempotency_key': 'idempotencyKey'}):
    'Atomically upsert and delete a private project’s text files under one expected project revision.'
    app_id: str
    project_id: str
    expected_revision: str
    upserts: list[CrowdyStudioProjectFileInput] | None | UnsetType = UNSET
    deletes: list[CrowdyStudioProjectFileDeleteInput] | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class SaveCrowdyStudioProjectInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_revision': 'expectedRevision', 'grid_id': 'gridId', 'server_module_name': 'serverModuleName', 'client_module_name': 'clientModuleName', 'pairing_preference': 'pairingPreference', 'sdk_version': 'sdkVersion', 'abi_version': 'abiVersion', 'idempotency_key': 'idempotencyKey'}):
    'Atomically save selected project metadata plus a batch of file upserts/deletes under one expected project revision. Crowdy Studio uses this to persist one coherent full-stack edit.'
    app_id: str
    project_id: str
    expected_revision: str
    grid_id: str | None | UnsetType = UNSET
    name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    server_module_name: str | None | UnsetType = UNSET
    client_module_name: str | None | UnsetType = UNSET
    pairing_preference: CrowdyStudioPairingPreference | None | UnsetType = UNSET
    sdk_version: str | None | UnsetType = UNSET
    abi_version: int | None | UnsetType = UNSET
    upserts: list[CrowdyStudioProjectFileInput] | None | UnsetType = UNSET
    deletes: list[CrowdyStudioProjectFileDeleteInput] | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class SaveCrowdyStudioProjectMetadataInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_revision': 'expectedRevision', 'grid_id': 'gridId', 'server_module_name': 'serverModuleName', 'client_module_name': 'clientModuleName', 'pairing_preference': 'pairingPreference', 'sdk_version': 'sdkVersion', 'abi_version': 'abiVersion', 'idempotency_key': 'idempotencyKey'}):
    'Optimistically save selected project metadata. Omitted fields remain unchanged; explicit null clears nullable metadata.'
    app_id: str
    project_id: str
    expected_revision: str
    grid_id: str | None | UnsetType = UNSET
    name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    server_module_name: str | None | UnsetType = UNSET
    client_module_name: str | None | UnsetType = UNSET
    pairing_preference: CrowdyStudioPairingPreference | None | UnsetType = UNSET
    sdk_version: str | None | UnsetType = UNSET
    abi_version: int | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class SetAppClientSettingsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'redirect_uris': 'redirectUris', 'client_type': 'clientType', 'launch_url': 'launchUrl'}):
    "Register/update an app's OAuth client settings for the portal handoff (requires manage_apps on the app)."
    app_id: str
    redirect_uris: list[str] | None | UnsetType = UNSET
    client_type: str | None | UnsetType = UNSET
    launch_url: str | None | UnsetType = UNSET


class SetAppReservedThroughputInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'app_id': 'appId', 'reserved_bytes_per_sec': 'reservedBytesPerSec'}):
    "Set or change an app's reserved REALTIME (UDP) capacity on the shared environment. Reservations are sold in two independent dimensions and this mutation sets one of them; read both back from App.reservedUdpBytesPerSec and App.reservedGraphqlOpsPerSec."
    org_id: str
    app_id: str
    reserved_bytes_per_sec: str


class SetChannelPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'creation_policy': 'creationPolicy', 'default_membership_policy': 'defaultMembershipPolicy', 'max_members': 'maxMembers', 'max_groups_per_user': 'maxGroupsPerUser'}):
    'Set the per-app channel creation/membership policy (app-admin only).'
    app_id: str
    creation_policy: str | None | UnsetType = UNSET
    default_membership_policy: str | None | UnsetType = UNSET
    max_members: int | None | UnsetType = UNSET
    max_groups_per_user: int | None | UnsetType = UNSET


class SetCrowdyStudioAgentAppPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'kill_switch': 'killSwitch', 'allowed_model_ids': 'allowedModelIds', 'allowed_tool_names': 'allowedToolNames', 'allowed_modes': 'allowedModes', 'allowed_risk_classes': 'allowedRiskClasses', 'turn_limits': 'turnLimits', 'session_limits': 'sessionLimits', 'player_day_limits': 'playerDayLimits', 'app_id': 'appId', 'expected_revision': 'expectedRevision', 'idempotency_key': 'idempotencyKey'}):
    "Patch an app's Agentic Studio policy. Requires manage_compute. Omitted fields stay unchanged; all supplied authority and limits are clamped to platform policy."
    enabled: bool | None | UnsetType = UNSET
    kill_switch: bool | None | UnsetType = UNSET
    allowed_model_ids: list[str] | None | UnsetType = UNSET
    allowed_tool_names: list[str] | None | UnsetType = UNSET
    allowed_modes: list[CrowdyStudioAgentMode] | None | UnsetType = UNSET
    allowed_risk_classes: list[CrowdyStudioAgentRiskClass] | None | UnsetType = UNSET
    turn_limits: CrowdyStudioAgentTurnLimitsInput | None | UnsetType = UNSET
    session_limits: CrowdyStudioAgentSessionLimitsInput | None | UnsetType = UNSET
    player_day_limits: CrowdyStudioAgentPlayerDayLimitsInput | None | UnsetType = UNSET
    retention: CrowdyStudioAgentRetentionPolicyInput | None | UnsetType = UNSET
    privacy: CrowdyStudioAgentPrivacyPolicyInput | None | UnsetType = UNSET
    funding: CrowdyStudioAgentFundingPolicyInput | None | UnsetType = UNSET
    app_id: str
    expected_revision: str | None | UnsetType = UNSET
    idempotency_key: str


class SetCrowdyStudioAgentOperatorAppKillInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'reason_code': 'reasonCode', 'expected_revision': 'expectedRevision', 'idempotency_key': 'idempotencyKey'}):
    'Operator-only per-app emergency kill. App managers cannot clear or override this state.'
    app_id: str
    killed: bool
    reason_code: str | None | UnsetType = UNSET
    reason: str | None | UnsetType = UNSET
    expected_revision: str | None | UnsetType = UNSET
    idempotency_key: str


class SetCrowdyStudioAgentPlatformPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'kill_switch': 'killSwitch', 'allowed_model_ids': 'allowedModelIds', 'allowed_tool_names': 'allowedToolNames', 'allowed_modes': 'allowedModes', 'allowed_risk_classes': 'allowedRiskClasses', 'turn_limits': 'turnLimits', 'session_limits': 'sessionLimits', 'player_day_limits': 'playerDayLimits', 'expected_revision': 'expectedRevision', 'kill_reason_code': 'killReasonCode', 'kill_reason': 'killReason', 'idempotency_key': 'idempotencyKey'}):
    'Operator-only platform policy patch. Omitted values stay unchanged; hard v1 privacy and retention maxima still apply.'
    enabled: bool | None | UnsetType = UNSET
    kill_switch: bool | None | UnsetType = UNSET
    allowed_model_ids: list[str] | None | UnsetType = UNSET
    allowed_tool_names: list[str] | None | UnsetType = UNSET
    allowed_modes: list[CrowdyStudioAgentMode] | None | UnsetType = UNSET
    allowed_risk_classes: list[CrowdyStudioAgentRiskClass] | None | UnsetType = UNSET
    turn_limits: CrowdyStudioAgentTurnLimitsInput | None | UnsetType = UNSET
    session_limits: CrowdyStudioAgentSessionLimitsInput | None | UnsetType = UNSET
    player_day_limits: CrowdyStudioAgentPlayerDayLimitsInput | None | UnsetType = UNSET
    retention: CrowdyStudioAgentRetentionPolicyInput | None | UnsetType = UNSET
    privacy: CrowdyStudioAgentPrivacyPolicyInput | None | UnsetType = UNSET
    funding: CrowdyStudioAgentFundingPolicyInput | None | UnsetType = UNSET
    expected_revision: str | None | UnsetType = UNSET
    kill_reason_code: str | None | UnsetType = UNSET
    kill_reason: str | None | UnsetType = UNSET
    idempotency_key: str


class SetCrowdyStudioLibraryFileArchivedInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'library_file_id': 'libraryFileId', 'expected_revision': 'expectedRevision', 'idempotency_key': 'idempotencyKey'}):
    'Optimistically archive or restore one caller-owned personal-library file.'
    app_id: str
    library_file_id: str
    expected_revision: str
    archived: bool
    idempotency_key: str | None | UnsetType = UNSET


class SetCrowdyStudioProjectArchivedInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'project_id': 'projectId', 'expected_revision': 'expectedRevision', 'idempotency_key': 'idempotencyKey'}):
    'Optimistically archive or unarchive one private project without deleting its files or provenance.'
    app_id: str
    project_id: str
    expected_revision: str
    archived: bool
    idempotency_key: str | None | UnsetType = UNSET


class SetCrowdyStudioProviderConsentInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    'Record or revoke the provider-data consent for one app.'
    app_id: str
    consented: bool


class SetGridPermissionLimitsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'permission_keys': 'permissionKeys'}):
    'Set the per-grid permission-key whitelist (writes the grid_permission_limits input table).'
    app_id: str
    grid_id: str
    permission_keys: list[str]


class SetHostedGameEnabledInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Developer: switch a hosted game off (DISABLED) or back on (LIVE). A TAKEN_DOWN game cannot be re-enabled here.'
    slug: str
    enabled: bool


class SetHostedGameListingInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Operator: list or unlist a hosted game.'
    slug: str
    listed: bool


class SetMemberRolesInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'group_id': 'groupId', 'user_id': 'userId', 'role_ids': 'roleIds'}):
    "Replace a member's roles in a group (the listed roles become their full set)."
    group_id: str
    user_id: str
    role_ids: list[str]


class SetQuotaInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'org_id': 'orgId', 'app_id': 'appId', 'tier_id': 'tierId', 'limit_value': 'limitValue', 'action_on_exceed': 'actionOnExceed', 'idempotency_key': 'idempotencyKey'}):
    org_id: str | None | UnsetType = UNSET
    app_id: str | None | UnsetType = UNSET
    tier_id: str | None | UnsetType = UNSET
    metric: str
    limit_value: str
    period: str | None | UnsetType = UNSET
    action_on_exceed: str | None | UnsetType = UNSET
    idempotency_key: str | None | UnsetType = UNSET


class SetRateCardInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'price_cents': 'priceCents', 'unit_label': 'unitLabel', 'unit_quantity': 'unitQuantity', 'acknowledge_repricing': 'acknowledgeRepricing', 'free_per_hour': 'freePerHour', 'free_units': 'freeUnits', 'free_period': 'freePeriod', 'free_per_month': 'freePerMonth'}):
    scope: RateScope
    metric: str
    price_cents: float | None | UnsetType = UNSET
    unit_label: str | None | UnsetType = UNSET
    unit_quantity: str | None | UnsetType = UNSET
    acknowledge_repricing: bool | None | UnsetType = UNSET
    free_per_hour: str | None | UnsetType = UNSET
    free_units: str | None | UnsetType = UNSET
    free_period: AllowancePeriod | None | UnsetType = UNSET
    free_per_month: str | None | UnsetType = UNSET
    reason: str


class SetTeamPolicyInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'creation_policy': 'creationPolicy', 'default_membership_policy': 'defaultMembershipPolicy', 'max_members': 'maxMembers', 'max_groups_per_user': 'maxGroupsPerUser'}):
    'Set the per-app team creation/membership policy (app-admin only).'
    app_id: str
    creation_policy: str | None | UnsetType = UNSET
    default_membership_policy: str | None | UnsetType = UNSET
    max_members: int | None | UnsetType = UNSET
    max_groups_per_user: int | None | UnsetType = UNSET


class SingleActorMessageInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'target_uuid': 'targetUuid', 'sequence_number': 'sequenceNumber'}):
    'Input for sending an actor-to-actor message: a message delivered only to the single actor identified by targetUuid. It is spatially routed (the sender must know the destination actor’s chunk), but unlike normal spatial messages it is NOT broadcast to other nearby actors and has no distance/decay.'
    app_id: str
    chunk: ChunkCoordinatesInput
    target_uuid: str
    payload: str
    sequence_number: int | None | UnsetType = UNSET


class SocialLoginCompleteInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Complete a federated sign-in from the provider callback.'
    provider: str
    code: str
    state: str


class SocialLoginStartInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'redirect_uri': 'redirectUri'}):
    'Begin a federated (social) sign-in.'
    provider: str
    redirect_uri: str


class TeleportRequestInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'chunk_address': 'chunkAddress', 'voxel_address': 'voxelAddress'}):
    app_id: str
    chunk_address: ChunkCoordinatesInput
    voxel_address: VoxelCoordinatesInput
    uuid: str


class TransferGridOwnershipInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'grid_id': 'gridId', 'new_owner_user_id': 'newOwnerUserId', 'expires_at': 'expiresAt'}):
    app_id: str
    grid_id: str
    new_owner_user_id: str
    tenure: GridTenure | None | UnsetType = UNSET
    expires_at: str | None | UnsetType = UNSET


class TransferPlayerCodeListingInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'listing_id': 'listingId', 'to_owner_kind': 'toOwnerKind', 'to_owner_ref': 'toOwnerRef'}):
    app_id: str
    listing_id: str
    to_owner_kind: PlayerCodeOwnerKind
    to_owner_ref: str


class UpdateAccessTierInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'tier_order': 'tierOrder', 'is_free': 'isFree', 'is_default': 'isDefault', 'price_cents': 'priceCents', 'billing_period': 'billingPeriod', 'stripe_price_id': 'stripePriceId', 'paypal_plan_id': 'paypalPlanId', 'permission_keys': 'permissionKeys'}):
    'Fields to update on an access tier. All fields are optional; omitted fields are left unchanged.'
    name: str | None | UnsetType = UNSET
    tier_order: int | None | UnsetType = UNSET
    is_free: bool | None | UnsetType = UNSET
    is_default: bool | None | UnsetType = UNSET
    price_cents: str | None | UnsetType = UNSET
    currency: str | None | UnsetType = UNSET
    billing_period: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    stripe_price_id: str | None | UnsetType = UNSET
    paypal_plan_id: str | None | UnsetType = UNSET
    permission_keys: list[str] | None | UnsetType = UNSET


class UpdateActorInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'avatar_id': 'avatarId', 'private_state': 'privateState', 'public_state': 'publicState'}):
    app_id: str | None | UnsetType = UNSET
    avatar_id: str | None | UnsetType = UNSET
    chunk: ChunkCoordinatesInput | None | UnsetType = UNSET
    private_state: str | None | UnsetType = UNSET
    public_state: str | None | UnsetType = UNSET


class UpdateActorStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'private_state': 'privateState', 'public_state': 'publicState'}):
    private_state: str | None | UnsetType = UNSET
    public_state: str | None | UnsetType = UNSET


class UpdateAppInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'wilderness_writes_open': 'wildernessWritesOpen'}):
    'Input payload for updating an app. All fields are optional; only fields that are provided are changed.'
    name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    visibility: AppVisibility | None | UnsetType = UNSET
    status: AppStatus | None | UnsetType = UNSET
    metadata: str | None | UnsetType = UNSET
    wilderness_writes_open: bool | None | UnsetType = UNSET


class UpdateAvatarAppStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'avatar_id': 'avatarId'}):
    app_id: str
    avatar_id: str
    state: str | None | UnsetType = UNSET


class UpdateAvatarInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    name: str | None | UnsetType = UNSET


class UpdateAvatarStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'public_state': 'publicState', 'private_state': 'privateState'}):
    public_state: str | None | UnsetType = UNSET
    private_state: str | None | UnsetType = UNSET


class UpdateChannelInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'group_id': 'groupId', 'membership_policy': 'membershipPolicy'}):
    'Update an existing channel. Omitted fields are left unchanged.'
    group_id: str
    name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    membership_policy: str | None | UnsetType = UNSET


class UpdateChunkLodsInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId'}):
    "Payload for updateChunkLods: replaces the chunk's entire LOD set. Only LODs are written; voxels, voxel states, chunk state and owner are preserved."
    app_id: str
    coordinates: ChunkCoordinatesInput
    lods: list[LodDataInput]


class UpdateChunkStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'chunk_state': 'chunkState'}):
    'Payload for updateChunkState: upserts ONLY the chunk-level opaque state blob; the voxel grid, per-voxel states and LODs are preserved.'
    app_id: str
    coordinates: ChunkCoordinatesInput
    chunk_state: str | None | UnsetType = UNSET


class UpdateGamertagInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    gamertag: str
    disambiguation: str


class UpdateGroupRoleInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'group_role_id': 'groupRoleId', 'role_name': 'roleName'}):
    'Update a custom group role. Omitted fields are left unchanged.'
    group_role_id: str
    role_name: str | None | UnsetType = UNSET
    permissions: list[str] | None | UnsetType = UNSET
    rank: int | None | UnsetType = UNSET


class UpdateOrgRoleInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'role_name': 'roleName'}):
    role_name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    permissions: list[str] | None | UnsetType = UNSET


class UpdateOrgTokenInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'expires_at': 'expiresAt', 'is_active': 'isActive'}):
    label: str | None | UnsetType = UNSET
    expires_at: str | None | UnsetType = UNSET
    is_active: bool | None | UnsetType = UNSET


class UpdateTeamInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'group_id': 'groupId', 'membership_policy': 'membershipPolicy'}):
    'Update an existing team. Omitted fields are left unchanged.'
    group_id: str
    name: str | None | UnsetType = UNSET
    description: str | None | UnsetType = UNSET
    membership_policy: str | None | UnsetType = UNSET


class UpdateUserStateInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    state: str | None | UnsetType = UNSET


class UpdateVoxelInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'voxel_type': 'voxelType'}):
    'Payload for updateVoxel: records (upserts) a single voxel edit in the voxel_updates log for one chunk.'
    app_id: str
    coordinates: ChunkCoordinatesInput
    location: VoxelCoordinatesInput
    voxel_type: float
    state: str | None | UnsetType = UNSET


class VoxelCoordinatesInput(msgspec.Struct, kw_only=True, omit_defaults=True):
    'Input form of a voxel position LOCAL to its chunk (see VoxelCoordinates). Signed 16-bit integers; in-bounds positions are 0-15 on each axis for a 16x16x16 chunk.'
    x: int
    y: int
    z: int


class VoxelStateInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'voxel_coord': 'voxelCoord', 'voxel_type': 'voxelType'}):
    'One per-voxel state entry to write to a chunk.'
    voxel_coord: VoxelCoordinatesInput
    voxel_type: int
    state: str | None | UnsetType = UNSET


class VoxelUpdateRequestInput(msgspec.Struct, kw_only=True, omit_defaults=True, rename={'app_id': 'appId', 'voxel_type': 'voxelType', 'voxel_state': 'voxelState', 'decay_rate': 'decayRate', 'sequence_number': 'sequenceNumber'}):
    'Input for sending a voxel update request to the UDP game server. This updates a single voxel (block) in a specific chunk. Voxel coordinates are relative to the chunk.'
    app_id: str
    chunk: ChunkCoordinatesInput
    uuid: str
    voxel: VoxelCoordinatesInput
    voxel_type: int
    voxel_state: str | None | UnsetType = UNSET
    distance: int | None | UnsetType = UNSET
    decay_rate: int | None | UnsetType = UNSET
    sequence_number: int | None | UnsetType = UNSET


__all__ = [
    'ActorFilterInput',
    'ActorUpdateRequestInput',
    'AdmitAppCodeInput',
    'AppMarketplaceFilterInput',
    'AssignGridOwnershipInput',
    'AssignGroupToGridInput',
    'AuthorizeAppInput',
    'BatchActorLookupInput',
    'BeginGamePublishInput',
    'BindCrowdyStudioGitHubInput',
    'ChannelMessageInput',
    'CheckAuthMethodInput',
    'CheckoutFilterInput',
    'ChunkCoordinatesInput',
    'ChunkUpdateInput',
    'ClaimGameHostingInput',
    'ClientAudioPacketInput',
    'ClientEventNotificationInput',
    'ClientTextPacketInput',
    'ClientVideoPacketInput',
    'CompleteLoginLinkInput',
    'CreateAccessTierInput',
    'CreateActorInput',
    'CreateAppInput',
    'CreateAvatarInput',
    'CreateChannelInput',
    'CreateCheckoutInput',
    'CreateCrowdyStudioProjectInput',
    'CreateGridChannelInput',
    'CreateGridInput',
    'CreateGroupRoleInput',
    'CreateOrgRoleInput',
    'CreateOrgTokenInput',
    'CreateOrganizationInput',
    'CreatePortalAuthorizationCodeInput',
    'CreateTeamInput',
    'CreateUserAppStateInput',
    'CrowdyStudioAgentFundingPolicyInput',
    'CrowdyStudioAgentPlayerDayLimitsInput',
    'CrowdyStudioAgentPrivacyPolicyInput',
    'CrowdyStudioAgentRetentionPolicyInput',
    'CrowdyStudioAgentSessionLimitsInput',
    'CrowdyStudioAgentTurnLimitsInput',
    'CrowdyStudioGitHubAtCommitInput',
    'CrowdyStudioGitHubDeleteFileInput',
    'CrowdyStudioGitHubFileInput',
    'CrowdyStudioGitHubProjectInput',
    'CrowdyStudioGitHubPutFileInput',
    'CrowdyStudioProjectFileDeleteInput',
    'CrowdyStudioProjectFileInput',
    'CurrentServerInput',
    'DefineAppFeatureInput',
    'DeleteGridInput',
    'ExchangePortalCodeInput',
    'ExecArtifactInput',
    'ExecBuildCrateInput',
    'ExecBuildFileInput',
    'ExecBuildInput',
    'ExecDeployInput',
    'GetChunkInput',
    'GetChunkLodsInput',
    'GetChunksByDistanceInput',
    'GetVoxelListInput',
    'GrantAppAccessInput',
    'GrantGridPermissionsInput',
    'GrantTierFeatureInput',
    'ImportCrowdyStudioProjectFileInput',
    'InviteOrgMemberInput',
    'LinkIdentityInput',
    'ListVoxelUpdatesByDistanceInput',
    'ListVoxelsInput',
    'LodDataInput',
    'LoginUserInput',
    'MintAppTokenInput',
    'MintGridTokenInput',
    'NearbyGridPermissionsInput',
    'NearbyGridsInput',
    'PublishCrowdyStudioCommonFileInput',
    'PublishFileInput',
    'RegisterUserInput',
    'ReinstateOrganizationInput',
    'RequestLoginLinkInput',
    'ResetPasswordInput',
    'RetireOrganizationInput',
    'RevokeGridPermissionsInput',
    'RevokeGroupFromGridInput',
    'RollbackVoxelUpdatesInput',
    'SaveCrowdyStudioLibraryFileInput',
    'SaveCrowdyStudioProjectFilesInput',
    'SaveCrowdyStudioProjectInput',
    'SaveCrowdyStudioProjectMetadataInput',
    'SetAppClientSettingsInput',
    'SetAppReservedThroughputInput',
    'SetChannelPolicyInput',
    'SetCrowdyStudioAgentAppPolicyInput',
    'SetCrowdyStudioAgentOperatorAppKillInput',
    'SetCrowdyStudioAgentPlatformPolicyInput',
    'SetCrowdyStudioLibraryFileArchivedInput',
    'SetCrowdyStudioProjectArchivedInput',
    'SetCrowdyStudioProviderConsentInput',
    'SetGridPermissionLimitsInput',
    'SetHostedGameEnabledInput',
    'SetHostedGameListingInput',
    'SetMemberRolesInput',
    'SetQuotaInput',
    'SetRateCardInput',
    'SetTeamPolicyInput',
    'SingleActorMessageInput',
    'SocialLoginCompleteInput',
    'SocialLoginStartInput',
    'TeleportRequestInput',
    'TransferGridOwnershipInput',
    'TransferPlayerCodeListingInput',
    'UpdateAccessTierInput',
    'UpdateActorInput',
    'UpdateActorStateInput',
    'UpdateAppInput',
    'UpdateAvatarAppStateInput',
    'UpdateAvatarInput',
    'UpdateAvatarStateInput',
    'UpdateChannelInput',
    'UpdateChunkLodsInput',
    'UpdateChunkStateInput',
    'UpdateGamertagInput',
    'UpdateGroupRoleInput',
    'UpdateOrgRoleInput',
    'UpdateOrgTokenInput',
    'UpdateTeamInput',
    'UpdateUserStateInput',
    'UpdateVoxelInput',
    'VoxelCoordinatesInput',
    'VoxelStateInput',
    'VoxelUpdateRequestInput',
]
