# GENERATED by scripts/unasync.py from src/crowdypy/domains/admin.py. Do not edit.
"""The studio-administration sub-clients under one namespace (``client.admin``).

Keeps the management surface a studio backend drives with a privileged token apart from
the player-facing one (sign-in, realtime, the world). These are the same instances the
client exposes at the top level: ``client.admin.billing`` is ``client.billing``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from crowdypy._sync.domains.app_access import AppAccessAPI
    from crowdypy._sync.domains.apps import AppsAPI
    from crowdypy._sync.domains.billing import BillingAPI
    from crowdypy._sync.domains.game_apps import GameAppsAPI
    from crowdypy._sync.domains.organizations import OrganizationsAPI
    from crowdypy._sync.domains.payments import PaymentsAPI
    from crowdypy._sync.domains.quotas import QuotasAPI
    from crowdypy._sync.domains.shared_environment import SharedEnvironmentAPI
    from crowdypy._sync.domains.usage import UsageAPI

__all__ = ["AdminAPI"]


class AdminAPI:
    """The studio-administration sub-clients, grouped for discoverability."""

    #: Organizations, members, RBAC roles and org API tokens.
    organizations: OrganizationsAPI
    #: The app registry, routing and player-code admission policy.
    apps: AppsAPI
    #: App access tiers and per-user access grants.
    app_access: AppAccessAPI
    #: Org wallets and per-app spend budgets.
    billing: BillingAPI
    #: Payment checkouts (wallet top-ups, purchases).
    payments: PaymentsAPI
    #: Usage quotas at the org and app scope.
    quotas: QuotasAPI
    #: Replication and GraphQL usage reporting.
    usage: UsageAPI
    #: Shared-environment publishing, runtime gating and auto-billing.
    shared_environment: SharedEnvironmentAPI
    #: App grids and grid runtime-permission administration.
    grids: GameAppsAPI

    def __init__(
        self,
        *,
        organizations: OrganizationsAPI,
        apps: AppsAPI,
        app_access: AppAccessAPI,
        billing: BillingAPI,
        payments: PaymentsAPI,
        quotas: QuotasAPI,
        usage: UsageAPI,
        shared_environment: SharedEnvironmentAPI,
        grids: GameAppsAPI,
    ) -> None:
        self.organizations = organizations
        self.apps = apps
        self.app_access = app_access
        self.billing = billing
        self.payments = payments
        self.quotas = quotas
        self.usage = usage
        self.shared_environment = shared_environment
        self.grids = grids
