# GENERATED by scripts/unasync.py from src/crowdypy/domains/avatars.py. Do not edit.
"""Avatars, the durable player identities, and their per-app state (``client.avatars``).

Avatars are distinct from realtime actors. Reads are owner-aware: anyone but the owner gets
``privateState`` as ``None``. Creating, updating and deleting an avatar and writing its state
are owner-only. Every call needs a bearer token (``UNAUTHENTICATED`` without one); ids are
BigInt decimal strings and state blobs base64.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain, omit_none
from crowdypy.utils import bigint

__all__ = ["AvatarsAPI"]


class AvatarsAPI(Domain):
    def list_for_user(self, user_id: str | int) -> list[dict[str, Any]]:
        """A user's avatars; ``privateState`` is ``None`` unless the caller is that user."""
        result: list[dict[str, Any]] = self._request(
            ops.USER_AVATARS, {"userId": bigint(user_id)}
        )
        return result

    def get(self, id: str | int) -> dict[str, Any]:
        """One avatar, owner-aware like :meth:`list_for_user`. Raises if it does not exist."""
        result: dict[str, Any] = self._request(ops.AVATAR_BY_ID, {"id": bigint(id)})
        return result

    def mine(self) -> list[dict[str, Any]]:
        """The caller's own avatars, full state included."""
        result: list[dict[str, Any]] = self._request(ops.MY_AVATARS)
        return result

    def app_state(self, app_id: str | int, avatar_id: str | int) -> dict[str, Any] | None:
        """One avatar's state in one app (any signed-in caller may read it), or ``None``."""
        result: dict[str, Any] | None = self._request(
            ops.AVATAR_APP_STATE, {"appId": bigint(app_id), "avatarId": bigint(avatar_id)}
        )
        return result

    def app_states(
        self, app_id: str | int, avatar_ids: Sequence[str | int]
    ) -> list[dict[str, Any]]:
        """Many avatars' state in one app in one call; avatars with none are left out."""
        result: list[dict[str, Any]] = self._request(
            ops.AVATAR_APP_STATES,
            {"appId": bigint(app_id), "avatarIds": [bigint(avatar_id) for avatar_id in avatar_ids]},
        )
        return result

    def create(self, input: inputs.CreateAvatarInput | Mapping[str, Any]) -> dict[str, Any]:
        """Create an avatar the caller owns; ``name`` is optional (default ``Default Avatar``)."""
        result: dict[str, Any] = self._request(ops.CREATE_AVATAR, {"input": input})
        return result

    def update(
        self, id: str | int, input: inputs.UpdateAvatarInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Change an avatar's mutable fields (its ``name``). Owner only."""
        result: dict[str, Any] = self._request(
            ops.UPDATE_AVATAR, {"id": bigint(id), "input": input}
        )
        return result

    def delete(self, id: str | int, idempotency_key: str | None = None) -> dict[str, Any]:
        """Permanently delete an avatar and return the deleted row. Owner only.

        With ``idempotency_key`` a retry replays the first result instead of deleting again.
        """
        result: dict[str, Any] = self._request(
            ops.DELETE_AVATAR, omit_none({"id": bigint(id), "idempotencyKey": idempotency_key})
        )
        return result

    def update_state(
        self, id: str | int, input: inputs.UpdateAvatarStateInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Replace an avatar's ``publicState`` and/or ``privateState`` (base64). Owner only.

        A blob left out of ``input`` is unchanged.
        """
        result: dict[str, Any] = self._request(
            ops.UPDATE_AVATAR_STATE, {"id": bigint(id), "input": input}
        )
        return result

    def update_app_state(
        self, input: inputs.UpdateAvatarAppStateInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Create or replace an avatar's ``state`` in one app. Owner-only write, public read."""
        result: dict[str, Any] = self._request(ops.UPDATE_AVATAR_APP_STATE, {"input": input})
        return result
