# GENERATED by scripts/unasync.py from src/crowdypy/domains/game_apps.py. Do not edit.
"""An app's grids, their title and their runtime permissions (``client.game_apps``).

A grid is a named 3D box of chunks that runtime (voxel) permissions are scoped to. Unless a
method says otherwise it needs app-admin, ``manage_apps`` on the org that owns the app
(``UNAUTHENTICATED`` / ``FORBIDDEN`` / ``SCOPE_MISSING`` without it). The permission
mutations recompute the grid's materialized effective ACL. Ids are BigInt decimal strings.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain
from crowdypy.utils import bigint

__all__ = ["GameAppsAPI"]


class GameAppsAPI(Domain):
    def ownership(self, app_id: str | int, grid_id: str | int) -> dict[str, Any] | None:
        """A grid's current title record, or ``None`` when it has no unexpired owner.

        Any bearer token may read it.
        """
        result: dict[str, Any] | None = self._request(
            ops.GRID_OWNERSHIP, {"appId": bigint(app_id), "gridId": bigint(grid_id)}
        )
        return result

    def assign_ownership(
        self, input: inputs.AssignGridOwnershipInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Give an unowned grid to one user. Title only: grant permissions separately."""
        result: dict[str, Any] = self._request(ops.ASSIGN_GRID_OWNERSHIP, {"input": input})
        return result

    def transfer_ownership(
        self, input: inputs.TransferGridOwnershipInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Transfer a grid's title, as its current owner or an app admin. Security-sensitive.

        Disables the grid's player modules pending the new owner's consent, wipes their
        state and removes the old owner's direct grants; the new owner gets no implicit
        grants.
        """
        result: dict[str, Any] = self._request(ops.TRANSFER_GRID_OWNERSHIP, {"input": input})
        return result

    def user_permissions(
        self, app_id: str | int, grid_id: str | int, user_id: str | int
    ) -> dict[str, Any]:
        """A user's effective (materialized) runtime permission keys on a grid."""
        result: dict[str, Any] = self._request(
            ops.GRID_USER_PERMISSIONS,
            {"appId": bigint(app_id), "gridId": bigint(grid_id), "userId": bigint(user_id)},
        )
        return result

    def nearby_permissions(
        self, input: inputs.NearbyGridPermissionsInput | Mapping[str, Any]
    ) -> list[dict[str, Any]]:
        """Every grid overlapping a chunk box, with a user's effective keys on each."""
        result: list[dict[str, Any]] = self._request(
            ops.NEARBY_GRID_PERMISSIONS, {"input": input}
        )
        return result

    def nearby_grids(
        self, input: inputs.NearbyGridsInput | Mapping[str, Any]
    ) -> list[dict[str, Any]]:
        """Every grid overlapping a chunk box: ids and bounds only, no permission keys.

        Player-safe: needs an app-scoped token for the app, not app-admin.
        """
        result: list[dict[str, Any]] = self._request(ops.NEARBY_GRIDS, {"input": input})
        return result

    def permission_limits(self, app_id: str | int, grid_id: str | int) -> dict[str, Any]:
        """A grid's permission-key whitelist; an empty list means no limit."""
        result: dict[str, Any] = self._request(
            ops.GRID_PERMISSION_LIMITS, {"appId": bigint(app_id), "gridId": bigint(grid_id)}
        )
        return result

    def open_permissions(self, app_id: str | int, grid_id: str | int) -> dict[str, Any]:
        """The keys a grid grants every player with active access to the app (an open build
        area, a public arena). An empty ``permissionKeys`` means the grid is not open."""
        result: dict[str, Any] = self._request(
            ops.GRID_OPEN_PERMISSIONS, {"appId": bigint(app_id), "gridId": bigint(grid_id)}
        )
        return result

    def group_grants(
        self, app_id: str | int, grid_id: str | int, group_id: str | int
    ) -> list[dict[str, Any]]:
        """A group's grants on a grid: inputs to the effective ACL, not the result."""
        result: list[dict[str, Any]] = self._request(
            ops.GRID_GROUP_GRANTS,
            {"appId": bigint(app_id), "gridId": bigint(grid_id), "groupId": bigint(group_id)},
        )
        return result

    def create_grid(
        self, input: inputs.CreateGridInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Create a grid from two opposite corner chunks.

        Refusals come back in the answer: ``grid`` is ``None`` and ``error`` names why (for
        example ``GRID_OVERLAPS_EXISTING``); on success ``error`` is ``NO_ERROR``.
        """
        result: dict[str, Any] = self._request(ops.CREATE_GRID, {"input": input})
        return result

    def delete_grid(
        self, input: inputs.DeleteGridInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Delete a studio-created peer grid so its box no longer blocks overlapping grids.

        Refusals come back in the answer: ``gridId`` is ``None`` and ``error`` names why
        (``GRID_NOT_FOUND``, ``CANNOT_DELETE_DEFAULT_WORLD_GRID``,
        ``GRID_HAS_NESTED_CHILDREN``); on success ``error`` is ``NO_ERROR``.
        """
        result: dict[str, Any] = self._request(ops.DELETE_GRID, {"input": input})
        return result

    def grant_permissions(
        self, input: inputs.GrantGridPermissionsInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Grant runtime permission keys directly to a user on a grid.

        The user needs active app access. Returns their effective keys after the grant.
        """
        result: dict[str, Any] = self._request(ops.GRANT_GRID_PERMISSIONS, {"input": input})
        return result

    def revoke_permissions(
        self, input: inputs.RevokeGridPermissionsInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Revoke a user's direct grants on a grid; omit ``permissionKeys`` to revoke them all.

        Group-derived keys are unaffected. Returns the user's remaining effective keys.
        """
        result: dict[str, Any] = self._request(ops.REVOKE_GRID_PERMISSIONS, {"input": input})
        return result

    def set_permission_limits(
        self, input: inputs.SetGridPermissionLimitsInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Replace a grid's permission-key whitelist; an empty list removes every limit.

        Narrowing it strips the dropped keys from every user on the grid.
        """
        result: dict[str, Any] = self._request(
            ops.SET_GRID_PERMISSION_LIMITS, {"input": input}
        )
        return result

    def set_open_permissions(
        self, input: inputs.SetGridOpenPermissionsInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Open a grid to every player: replace the keys it grants each player with active
        access to the app, within its limits; players who gain access later get them too. An
        empty ``permissionKeys`` closes the grid.

        The most specific grid covering a chunk decides a voxel write there, so a zone nested
        in the world grid that everyone may build in must grant ``update_voxel_data`` itself.
        Refused with ``BAD_REQUEST`` for the app's world grid (open already), any of the four
        player-code keys, a key that is not an active grid key, and a 33rd open grid in one
        app. Needs ``manage_apps``.
        """
        result: dict[str, Any] = self._request(
            ops.SET_GRID_OPEN_PERMISSIONS, {"input": input}
        )
        return result

    def assign_group(
        self, input: inputs.AssignGroupToGridInput | Mapping[str, Any]
    ) -> list[dict[str, Any]]:
        """Grant permission keys to a group, or one of its roles, on a grid.

        Returns the group's grants on the grid after the assignment.
        """
        result: list[dict[str, Any]] = self._request(
            ops.ASSIGN_GROUP_TO_GRID, {"input": input}
        )
        return result

    def revoke_group(
        self, input: inputs.RevokeGroupFromGridInput | Mapping[str, Any]
    ) -> list[dict[str, Any]]:
        """Revoke a group's (or role's) grants on a grid; omit ``permissionKeys`` for all.

        Returns the group's remaining grants on the grid.
        """
        result: list[dict[str, Any]] = self._request(
            ops.REVOKE_GROUP_FROM_GRID, {"input": input}
        )
        return result
