# GENERATED by scripts/unasync.py from src/crowdypy/domains/host.py. Do not edit.
"""Game-host election and the actor liveness heartbeat (``client.host``).

The elected host is the same on every API replica: the user whose earliest still-connected
actor was created first. :meth:`HostAPI.heartbeat` keeps the caller's actors fresh, and so
host-eligible, and answers the freshly elected host in the same round-trip; call it on an
interval shorter than the server's freshness window. :meth:`HostAPI.am_i_host` is for UI
only: a hub decides host-only actions from its caller. Every call needs a bearer token
(``UNAUTHENTICATED`` without one).
"""

from __future__ import annotations

from typing import Any

from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain
from crowdypy.utils import bigint

__all__ = ["HostAPI"]


class HostAPI(Domain):
    def get(self, app_id: str | int) -> dict[str, Any] | None:
        """The app's elected host, or ``None`` when it has no actors."""
        result: dict[str, Any] | None = self._request(
            ops.GAME_HOST, {"appId": bigint(app_id)}
        )
        return result

    def am_i_host(self, app_id: str | int) -> bool:
        """Whether the caller is the app's elected host. Not authoritative for mutations."""
        return bool(self._request(ops.AM_I_GAME_HOST, {"appId": bigint(app_id)}))

    def heartbeat(self, app_id: str | int) -> dict[str, Any] | None:
        """Refresh the caller's actors in an app and return the freshly elected host.

        ``None`` when the app has no fresh actors.
        """
        result: dict[str, Any] | None = self._request(
            ops.ACTOR_HEARTBEAT, {"appId": bigint(app_id)}
        )
        return result
