# GENERATED by scripts/unasync.py from src/crowdypy/domains/marketplace.py. Do not edit.
"""Grid claims and the app's player-code moderation (``client.marketplace``).

The grid claim flows (the policy, claim requests, chunk and ownership claims, invites)
are gameplay: call them on a per-game client holding the app-scoped token. The studio
moderation calls (the admission queue, listing administration, ownership transfer and
setting the claim policy) are studio administration: call them on the identity client
(session token), with the app permission each one names. Ids are BigInts and accept an
``int`` or a decimal string.

Players publish and install mods through ck-exec, not here.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from crowdypy._generated import enums, inputs
from crowdypy._generated import operations as ops
from crowdypy._operation import inline_operation
from crowdypy._sync.domains._base import Domain, omit_none
from crowdypy.utils import bigint

__all__ = ["MarketplaceAPI"]


# CrowdyCPP's MarketplaceAPI sends this; CrowdyJS does not.
APP_LISTING_VERSIONS = inline_operation(
    "MarketplaceAppListingVersions",
    "query",
    "appPlayerCodeListingVersions",
    "query MarketplaceAppListingVersions($appId: BigInt!, $listingId: String!) { "
    "appPlayerCodeListingVersions(appId: $appId, listingId: $listingId) { versionId listingId "
    "versionNo serverArtifactHashes clientArtifactHashes requirements { serverArtifactHash "
    "clientArtifactHash } capabilitySummaryJson capabilityHash openSource licenseText "
    "createdAt } }",
)
INLINE_OPERATIONS = (APP_LISTING_VERSIONS,)


class MarketplaceAPI(Domain):
    def grid_claim_policy(self, app_id: str | int) -> str:
        """The app's grid claim policy: ``SELF_CLAIM``, ``APPROVAL``, ``INVITE`` or ``MARKETPLACE_ONLY``."""
        result: str = self._request(
            ops.MARKETPLACE_GRID_CLAIM_POLICY, {"appId": bigint(app_id)}
        )
        return result

    def grid_claim_requests(self, app_id: str | int) -> list[dict[str, Any]]:
        """Pending grid claim requests.

        Designated approvers (and studio staff holding ``manage_compute``) see the app's
        queue; any other player sees their own requests.
        """
        result: list[dict[str, Any]] = self._request(
            ops.MARKETPLACE_GRID_CLAIM_REQUESTS, {"appId": bigint(app_id)}
        )
        return result

    def claim_grid_ownership(self, app_id: str | int, grid_id: str | int) -> dict[str, Any]:
        """Claim an existing, unowned grid under the app's claim policy (authorized by the server).

        ``SELF_CLAIM`` assigns it at once, ``APPROVAL`` files a request for the approvers,
        ``INVITE`` spends a standing invite and ``MARKETPLACE_ONLY`` refuses. Answers the
        ``policy``, whether ``ownershipAssigned``, and the ``claimRequestId`` it filed.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_CLAIM_GRID_OWNERSHIP,
            {"appId": bigint(app_id), "gridId": bigint(grid_id)},
        )
        return result

    def claim_grid_chunk(
        self, app_id: str | int, chunk: inputs.ChunkCoordinatesInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Create and claim a one-chunk grid in one step, as the caller. ``SELF_CLAIM`` apps only.

        The server refuses a protected or overlapping chunk, and answers the grid's
        authoritative bounds, its ownership and the caller's effective build and mod
        permission keys. ``chunk`` holds ``x``, ``y`` and ``z`` as BigInt decimal strings.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_CLAIM_GRID_CHUNK, {"appId": bigint(app_id), "chunk": chunk}
        )
        return result

    def release_claimed_grid(self, app_id: str | int, grid_id: str | int) -> dict[str, Any]:
        """Release a grid made by :meth:`claim_grid_chunk`, so its chunk can be claimed again.

        The caller must still own it; grids that came about any other way cannot be
        released.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_RELEASE_CLAIMED_GRID,
            {"appId": bigint(app_id), "gridId": bigint(grid_id)},
        )
        return result

    def decide_grid_claim(
        self, app_id: str | int, request_id: str, approve: bool
    ) -> dict[str, Any]:
        """Approve or deny a pending claim request (``APPROVAL`` policy).

        For the app's designated approvers or studio staff holding ``manage_compute``.
        Approval assigns the grid to the requester.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_DECIDE_GRID_CLAIM,
            {"appId": bigint(app_id), "requestId": request_id, "approve": approve},
        )
        return result

    def issue_grid_claim_invite(
        self, app_id: str | int, grid_id: str | int, invitee_user_id: str | int
    ) -> bool:
        """Issue a standing invite to claim a grid (``INVITE`` policy).

        For designated approvers or studio staff holding ``manage_compute``; the invitee
        then calls :meth:`claim_grid_ownership`.
        """
        return bool(
            self._request(
                ops.MARKETPLACE_ISSUE_GRID_CLAIM_INVITE,
                {
                    "appId": bigint(app_id),
                    "gridId": bigint(grid_id),
                    "inviteeUserId": bigint(invitee_user_id),
                },
            )
        )

    def admission_queue(self, app_id: str | int) -> list[dict[str, Any]]:
        """The admission queue: every listing not killed, with its allow-list standing.

        Identity session, ``view_compute_diagnostics``. Standing is ``ADMITTED``,
        ``PENDING`` or ``REVOKED``.
        """
        result: list[dict[str, Any]] = self._request(
            ops.MARKETPLACE_ADMISSION_QUEUE, {"appId": bigint(app_id)}
        )
        return result

    def app_listings(
        self, app_id: str | int, include_delisted: bool | None = None
    ) -> list[dict[str, Any]]:
        """The app's code listings, newest first: the studio catalog administration view.

        Identity session, ``view_compute_diagnostics``. ``include_delisted`` adds the
        delisted and killed listings, for moderation history.
        """
        result: list[dict[str, Any]] = self._request(
            ops.MARKETPLACE_APP_LISTINGS,
            omit_none({"appId": bigint(app_id), "includeDelisted": include_delisted}),
        )
        return result

    def app_acquisitions(self, app_id: str | int) -> list[dict[str, Any]]:
        """Every code acquisition in the app, newest first: the studio audit view.

        Identity session, ``view_compute_diagnostics``. Uninstalling never deletes one.
        """
        result: list[dict[str, Any]] = self._request(
            ops.MARKETPLACE_APP_ACQUISITIONS, {"appId": bigint(app_id)}
        )
        return result

    def transfer_listing(
        self, input: inputs.TransferPlayerCodeListingInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Move a listing between personal and org ownership, with an audit record.

        Identity session. The caller must own the listing, or hold ``manage_compute`` in
        the org that does; a transfer to an org needs ``manage_compute`` in that org.
        Ownership carries listing control and source access.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_TRANSFER_LISTING, {"input": input}
        )
        return result

    def set_listing_status(
        self,
        app_id: str | int,
        listing_id: str,
        status: enums.PlayerCodeListingStatus | str,
    ) -> dict[str, Any]:
        """Set a listing's catalog status.

        Identity session. ``DELISTED`` and ``ACTIVE`` are the owner's (delisting only stops
        new acquisitions; installs keep their pinned versions); ``KILLED`` is the studio
        kill and needs ``manage_compute`` on the app.
        """
        result: dict[str, Any] = self._request(
            ops.MARKETPLACE_SET_LISTING_STATUS,
            {"appId": bigint(app_id), "listingId": listing_id, "status": status},
        )
        return result

    def set_grid_claim_policy(
        self,
        app_id: str | int,
        policy: enums.GridClaimPolicy | str,
        approver_user_ids: Sequence[str | int] | None = None,
    ) -> str:
        """Set how a player claim confers grid ownership in the app, and answer the policy.

        Identity session, ``manage_apps``. ``approver_user_ids`` are the players who may
        approve claims under ``APPROVAL``; with none, studio staff holding
        ``manage_compute`` do. ``MARKETPLACE_ONLY`` is refused (``FEATURE_DISABLED``).
        Changing the policy never revokes an existing ownership.
        """
        if isinstance(approver_user_ids, str):
            raise TypeError("approver_user_ids is a sequence of user ids, not one string")
        approvers = (
            [bigint(user_id) for user_id in approver_user_ids]
            if approver_user_ids is not None
            else None
        )
        result: str = self._request(
            ops.MARKETPLACE_SET_GRID_CLAIM_POLICY,
            omit_none({"appId": bigint(app_id), "policy": policy, "approverUserIds": approvers}),
        )
        return result

    def app_listing_versions(self, app_id: str | int, listing_id: str) -> list[dict[str, Any]]:
        """A listing's immutable published versions, newest first, with their artifact
        hashes. Needs ``view_compute_diagnostics``."""
        result: list[dict[str, Any]] = self._request(
            APP_LISTING_VERSIONS, {"appId": bigint(app_id), "listingId": listing_id}
        )
        return result
