# GENERATED by scripts/unasync.py from src/crowdypy/domains/portal.py. Do not edit.
"""App-scoped tokens and the portal's authorization-code flow (``client.portal``).

Gameplay needs a short-lived **app-scoped token** per app. Mint one on the identity
client with :meth:`PortalAPI.mint_app_token` and hand it to a per-game client pointed at
the ``game_api_url`` the mint returns. The token is also the 64-octet HMAC key the native
replication client signs every datagram with.

A native client that refreshes while connected names the replication server it is on
(:meth:`PortalAPI.refresh` with ``current_server``) so the Game API authorizes the new
token on that same server; a server silently drops datagrams for a token it was never
told about.

Hosted sign-in (CrowdyJS ``portal.signIn`` / ``handleSignInCallback`` /
``handleAuthorizeRequest``) navigates a browser tab and reads its location, so it is a
browser exclusion here, as in CrowdyCPP. The PKCE steps underneath it are not:
:meth:`PortalAPI.begin_entry` builds the authorize URL (open it in the system browser)
and :meth:`PortalAPI.complete_entry` exchanges the code your redirect receives.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol
from urllib.parse import parse_qs, urlencode, urlsplit, urlunsplit

import msgspec

from crowdypy._operation import inline_operation
from crowdypy._sync.domains._base import Domain, omit_none
from crowdypy._sync.graphql import GraphQLClient
from crowdypy.pkce import generate_pkce_pair, generate_state
from crowdypy.session import SessionStore
from crowdypy.utils import bigint
from crowdypy.domains.portal import AppAuthorizationGrant, AppTokenResponse, AuthorizedServer, CurrentServer, MemoryPkceStore, PkceStore, PortalConsentRequiredError  # one class in both clients

__all__ = [
    "AppAuthorizationGrant",
    "AppTokenResponse",
    "AuthorizedServer",
    "CurrentServer",
    "MemoryPkceStore",
    "PkceStore",
    "PortalAPI",
    "PortalConsentRequiredError",
    "default_hosted_sign_in_url",
    "is_hosted_sign_in_required_error",
]
















def default_hosted_sign_in_url(graphql_endpoint: str) -> str:
    """Studio's hosted ``/authorize`` for the API an endpoint names.

    ``ck.<tier>.`` maps to ``studio.<tier>.``; a local API on port 3000 maps to the local
    Studio on 3001.
    """
    parts = urlsplit(graphql_endpoint)
    host = (parts.hostname or "").lower()
    if host in ("localhost", "127.0.0.1"):
        return f"{parts.scheme}://{host}:3001/authorize"
    if host.startswith("ck."):
        return f"https://studio.{host[len('ck.') :]}/authorize"
    raise ValueError(
        f"Cannot derive the hosted sign-in page from {graphql_endpoint}; pass authorize_url "
        "explicitly (the tier's Studio origin + /authorize)."
    )


def is_hosted_sign_in_required_error(error: object) -> bool:
    """The API refused direct sign-in because the caller presented a browser origin."""
    code = getattr(error, "code", None)
    if code == "HOSTED_SIGN_IN_REQUIRED":
        return True
    for entry in getattr(error, "graphql_errors", None) or ():
        if (entry.get("extensions") or {}).get("code") == "HOSTED_SIGN_IN_REQUIRED":
            return True
    message = str(error)
    return (
        "HOSTED_SIGN_IN_REQUIRED" in message or "only available to first-party" in message.lower()
    )


_APP_TOKEN_FIELDS = (
    "token gameTokenId appId expiresAt gameApiUrl gameApiWsUrl discoveryUrl launchUrl"
)

MINT_APP_TOKEN = inline_operation(
    "MintAppToken",
    "mutation",
    "mintAppToken",
    "mutation MintAppToken($input: MintAppTokenInput!) { mintAppToken(input: $input) { "
    + _APP_TOKEN_FIELDS
    + " } }",
)
CREATE_PORTAL_AUTHORIZATION_CODE = inline_operation(
    "CreatePortalAuthorizationCode",
    "mutation",
    "createPortalAuthorizationCode",
    "mutation CreatePortalAuthorizationCode($input: CreatePortalAuthorizationCodeInput!) { "
    "createPortalAuthorizationCode(input: $input) { code redirectUri expiresAt } }",
)
EXCHANGE_PORTAL_CODE = inline_operation(
    "ExchangePortalCode",
    "mutation",
    "exchangePortalCode",
    "mutation ExchangePortalCode($input: ExchangePortalCodeInput!) { exchangePortalCode(input: $input) { "
    + _APP_TOKEN_FIELDS
    + " } }",
)
REFRESH_APP_TOKEN = inline_operation(
    "RefreshAppToken",
    "mutation",
    "refreshAppToken",
    "mutation RefreshAppToken { refreshAppToken { " + _APP_TOKEN_FIELDS + " } }",
)
REFRESH_APP_TOKEN_ON_SERVER = inline_operation(
    "RefreshAppTokenOnServer",
    "mutation",
    "refreshAppToken",
    "mutation RefreshAppTokenOnServer($currentServer: CurrentServerInput) { "
    "refreshAppToken(currentServer: $currentServer) { "
    + _APP_TOKEN_FIELDS
    + " authorizedServer { ip4 clientPort } } }",
)
PORTAL_CONSENT = inline_operation(
    "PortalConsent",
    "query",
    "portalConsent",
    "query PortalConsent($appId: BigInt!) { portalConsent(appId: $appId) { "
    "appId appName trusted alreadyGranted consentRequired } }",
)
AUTHORIZE_APP = inline_operation(
    "AuthorizeApp",
    "mutation",
    "authorizeApp",
    "mutation AuthorizeApp($input: AuthorizeAppInput!) { authorizeApp(input: $input) { "
    "grantId appId status scopes } }",
)
REVOKE_APP_AUTHORIZATION = inline_operation(
    "RevokeAppAuthorization",
    "mutation",
    "revokeAppAuthorization",
    "mutation RevokeAppAuthorization($appId: BigInt!) { revokeAppAuthorization(appId: $appId) }",
)
MY_AUTHORIZED_APPS = inline_operation(
    "MyAuthorizedApps",
    "query",
    "myAuthorizedApps",
    "query MyAuthorizedApps { myAuthorizedApps { "
    "grantId appId appName scopes status grantedAt revokedAt } }",
)
SET_APP_CLIENT_SETTINGS = inline_operation(
    "SetAppClientSettings",
    "mutation",
    "setAppClientSettings",
    "mutation SetAppClientSettings($input: SetAppClientSettingsInput!) { "
    "setAppClientSettings(input: $input) { appId appName trusted consentRequired } }",
)

INLINE_OPERATIONS = (
    MINT_APP_TOKEN,
    CREATE_PORTAL_AUTHORIZATION_CODE,
    EXCHANGE_PORTAL_CODE,
    REFRESH_APP_TOKEN,
    REFRESH_APP_TOKEN_ON_SERVER,
    PORTAL_CONSENT,
    AUTHORIZE_APP,
    REVOKE_APP_AUTHORIZATION,
    MY_AUTHORIZED_APPS,
    SET_APP_CLIENT_SETTINGS,
)


def _server_input(server: CurrentServer | Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(server, CurrentServer):
        return {"ip4": server.ip4, "clientPort": server.client_port}
    port = server.get("clientPort", server.get("client_port"))
    return {"ip4": str(server["ip4"]), "clientPort": int(port) if port is not None else 0}


def _query_params(url_or_query: str) -> dict[str, str]:
    query = urlsplit(url_or_query).query if "://" in url_or_query else url_or_query.lstrip("?")
    return {key: values[0] for key, values in parse_qs(query, keep_blank_values=True).items()}


class PortalAPI(Domain):
    def __init__(
        self,
        graphql: GraphQLClient,
        session: SessionStore,
        pkce_store: PkceStore | None = None,
    ) -> None:
        super().__init__(graphql)
        self._session = session
        self._pkce_store: PkceStore = pkce_store or MemoryPkceStore()

    def mint_app_token(self, app_id: str | int) -> AppTokenResponse:
        """Mint an app-scoped token on the identity client. It is NOT stored here.

        Give it to the per-game client (``game.set_token(minted.token)``).
        """
        payload = self._request(MINT_APP_TOKEN, {"input": {"appId": bigint(app_id)}})
        return msgspec.convert(payload, AppTokenResponse)

    def create_authorization_code(
        self,
        app_id: str | int,
        code_challenge: str,
        redirect_uri: str,
        code_challenge_method: str | None = None,
    ) -> dict[str, Any]:
        input_ = omit_none(
            {
                "appId": bigint(app_id),
                "codeChallenge": code_challenge,
                "codeChallengeMethod": code_challenge_method,
                "redirectUri": redirect_uri,
            }
        )
        result: dict[str, Any] = self._request(
            CREATE_PORTAL_AUTHORIZATION_CODE, {"input": input_}
        )
        return result

    def exchange_code(self, code: str, code_verifier: str | None = None) -> AppTokenResponse:
        """Exchange an authorization code for an app token, and hold it on this client."""
        payload = self._request(
            EXCHANGE_PORTAL_CODE,
            {"input": omit_none({"code": code, "codeVerifier": code_verifier})},
        )
        token = msgspec.convert(payload, AppTokenResponse)
        self._session.set_token(token.token)
        return token

    def refresh(
        self, current_server: CurrentServer | Mapping[str, Any] | None = None
    ) -> AppTokenResponse:
        """Refresh this client's app token and hold the new one.

        With ``current_server`` (the ``ip4`` and ``client_port`` the client is connected
        to) the Game API also authorizes the new token on that server and answers
        ``authorized_server``: when it is set, keep the socket and sign with the new
        token; when it is ``None``, place again.
        """
        if current_server is None:
            payload = self._request(REFRESH_APP_TOKEN, {})
        else:
            payload = self._request(
                REFRESH_APP_TOKEN_ON_SERVER, {"currentServer": _server_input(current_server)}
            )
        token = msgspec.convert(payload, AppTokenResponse)
        self._session.set_token(token.token)
        return token

    def get_consent(self, app_id: str | int) -> dict[str, Any]:
        result: dict[str, Any] = self._request(PORTAL_CONSENT, {"appId": bigint(app_id)})
        return result

    def authorize_app(
        self, app_id: str | int, scopes: Sequence[str] | None = None
    ) -> AppAuthorizationGrant:
        input_: dict[str, Any] = {"appId": bigint(app_id)}
        if scopes is not None:
            input_["scopes"] = list(scopes)
        return msgspec.convert(
            self._request(AUTHORIZE_APP, {"input": input_}), AppAuthorizationGrant
        )

    def revoke_app_authorization(self, app_id: str | int) -> bool:
        return bool(self._request(REVOKE_APP_AUTHORIZATION, {"appId": bigint(app_id)}))

    def my_authorized_apps(self) -> list[AppAuthorizationGrant]:
        return msgspec.convert(self._request(MY_AUTHORIZED_APPS), list[AppAuthorizationGrant])

    def set_app_client_settings(
        self,
        app_id: str | int,
        redirect_uris: Sequence[str] | None = None,
        client_type: str | None = None,
        launch_url: str | None = None,
    ) -> dict[str, Any]:
        input_ = omit_none(
            {
                "appId": bigint(app_id),
                "redirectUris": list(redirect_uris) if redirect_uris is not None else None,
                "clientType": client_type,
                "launchUrl": launch_url,
            }
        )
        result: dict[str, Any] = self._request(SET_APP_CLIENT_SETTINGS, {"input": input_})
        return result

    def begin_entry(
        self, app_id: str | int, authorize_url: str, redirect_uri: str, state: str | None = None
    ) -> str:
        """Start the PKCE flow: remember a verifier and return the authorize URL to open.

        The verifier never leaves this process; :meth:`complete_entry` looks it up by the
        ``state`` the redirect carries back.
        """
        state = state or generate_state()
        pkce = generate_pkce_pair()
        self._pkce_store.set(state, pkce.verifier)
        parts = urlsplit(authorize_url)
        params = {
            key: values[0] for key, values in parse_qs(parts.query, keep_blank_values=True).items()
        }
        params.update(
            {
                "app_id": str(app_id),
                "code_challenge": pkce.challenge,
                "code_challenge_method": pkce.method,
                "redirect_uri": redirect_uri,
                "state": state,
            }
        )
        return urlunsplit(
            (parts.scheme, parts.netloc, parts.path, urlencode(params), parts.fragment)
        )

    def complete_entry(self, redirect: str) -> AppTokenResponse | None:
        """Finish the PKCE flow from the URL (or query string) your redirect received.

        Returns ``None`` when it carries no ``code``, and for a GitHub App callback, whose
        ``code`` is GitHub's and must never be spent as a portal code.
        """
        params = _query_params(redirect)
        if {"github", "installation_id", "setup_action"} & params.keys():
            return None
        code = params.get("code")
        if not code:
            return None
        state = params.get("state", "")
        verifier = self._pkce_store.get(state)
        token = self.exchange_code(code, verifier)
        if state:
            self._pkce_store.remove(state)
        return token
