# GENERATED by scripts/unasync.py from src/crowdypy/domains/state.py. Do not edit.
"""The signed-in user's per-app state (``client.state``).

One row per user and app, keyed by ``appId`` + ``userId``: a place for small per-player,
per-game data. ``state`` is base64-encoded binary (``None`` once cleared) and ``appId`` a
BigInt decimal string. Every call needs a bearer token (``UNAUTHENTICATED`` without one) and
reads or writes only the caller's own rows.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain
from crowdypy.utils import bigint

__all__ = ["StateAPI"]


class StateAPI(Domain):
    def get_one(self, app_id: str | int) -> dict[str, Any] | None:
        """The caller's state for one app, or ``None`` when there is no row."""
        result: dict[str, Any] | None = self._request(
            ops.USER_APP_STATE, {"appId": bigint(app_id)}
        )
        return result

    def get_all(self) -> list[dict[str, Any]]:
        """Every per-app state row of the caller, most recently updated first."""
        result: list[dict[str, Any]] = self._request(ops.USER_APP_STATES)
        return result

    def update(
        self, input: inputs.CreateUserAppStateInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Create or replace the caller's state for ``appId``; omit or null ``state`` to clear it.

        ``BAD_USER_INPUT`` for a malformed input.
        """
        result: dict[str, Any] = self._request(ops.UPDATE_USER_APP_STATE, {"input": input})
        return result

    def delete(self, app_id: str | int) -> dict[str, Any]:
        """Delete the caller's state row for one app and return it. Destructive.

        Raises when the caller has no row for that app (not found).
        """
        result: dict[str, Any] = self._request(
            ops.DELETE_USER_APP_STATE, {"appId": bigint(app_id)}
        )
        return result
