# GENERATED by scripts/unasync.py from src/crowdypy/domains/teams.py. Do not edit.
"""Teams: app-scoped player groups with roles and delegated management (``client.teams``).

A team is a named set of players in one app with a role and permission model, built on
the same groups as channels. Unlike a channel, it has no message path. These methods
cover a team's lifecycle: creating, listing and fetching teams, membership (join,
request to join, leave, add, remove), roles, and the app's team policy.

Teams are gameplay: call these on a per-game client holding the app-scoped token
(``client.portal.mint_app_token``). Ids are BigInts and accept an ``int`` or a decimal
string. Membership, role and policy changes need a team permission (``manage_group``,
``manage_members``, ``manage_roles``) or app-admin (``manage_apps``); a refusal raises
:class:`~crowdypy.errors.CrowdyGraphQLError` with a code such as ``UNAUTHENTICATED``,
``SCOPE_MISSING`` or ``FORBIDDEN``.
"""

from __future__ import annotations

import builtins  # TeamsAPI.list shadows the builtin in the class's annotations
from collections.abc import Mapping
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain, omit_none
from crowdypy.utils import bigint

__all__ = ["TeamsAPI"]


class TeamsAPI(Domain):
    def mine(self, app_id: str | int) -> builtins.list[dict[str, Any]]:
        """The caller's teams in an app, with the caller's roles and effective permissions."""
        result: builtins.list[dict[str, Any]] = self._request(
            ops.MY_TEAMS, {"appId": bigint(app_id)}
        )
        return result

    def list(self, app_id: str | int) -> builtins.list[dict[str, Any]]:
        """Every active team in an app, not only the caller's (that is :meth:`mine`)."""
        result: builtins.list[dict[str, Any]] = self._request(
            ops.TEAMS, {"appId": bigint(app_id)}
        )
        return result

    def get(self, group_id: str | int) -> dict[str, Any]:
        """One team by its group id. Raises when the id is not a team (a channel, or nothing)."""
        result: dict[str, Any] = self._request(ops.TEAM, {"groupId": bigint(group_id)})
        return result

    def members(self, group_id: str | int) -> builtins.list[dict[str, Any]]:
        """A team's members, pending join requests included, with their status and roles."""
        result: builtins.list[dict[str, Any]] = self._request(
            ops.TEAM_MEMBERS, {"groupId": bigint(group_id)}
        )
        return result

    def roles(self, group_id: str | int) -> builtins.list[dict[str, Any]]:
        """A team's roles, the system ``leader`` role included, and the permission keys each grants."""
        result: builtins.list[dict[str, Any]] = self._request(
            ops.TEAM_ROLES, {"groupId": bigint(group_id)}
        )
        return result

    def policy(self, app_id: str | int) -> dict[str, Any]:
        """The app's team policy: who may create teams, and new teams' membership policy.

        Falls back to the app defaults when none is set.
        """
        result: dict[str, Any] = self._request(ops.TEAM_POLICY, {"appId": bigint(app_id)})
        return result

    def create(self, input: inputs.CreateTeamInput | Mapping[str, Any]) -> dict[str, Any]:
        """Create a team; the caller becomes its owner with the ``leader`` role (every permission).

        The app's creation policy (``admin``, ``member`` or ``anyone``) decides whether the
        caller may. The team takes the app's default membership policy unless
        ``membership_policy`` overrides it. ``name`` is at most 128 characters and unique in
        the app. Raises ``BAD_USER_INPUT`` (a long or taken name) or ``FORBIDDEN`` (the
        policy refuses).
        """
        result: dict[str, Any] = self._request(ops.CREATE_TEAM, {"input": input})
        return result

    def update(self, input: inputs.UpdateTeamInput | Mapping[str, Any]) -> dict[str, Any]:
        """Change a team's name, description and/or membership policy. Needs ``manage_group``.

        Fields left out stay as they are.
        """
        result: dict[str, Any] = self._request(ops.UPDATE_TEAM, {"input": input})
        return result

    def remove(self, group_id: str | int, idempotency_key: str | None = None) -> bool:
        """Delete a team. Needs ``manage_group``.

        Destructive: its members, roles and any grid grants it conferred go with it, and the
        affected grids' access is recomputed. ``idempotency_key`` makes a retry safe: the
        same key with the same ``group_id`` answers the first result instead of deleting
        again, with another ``group_id`` it raises ``IDEMPOTENCY_CONFLICT``. Keys expire
        after 24 hours.
        """
        variables = omit_none({"groupId": bigint(group_id), "idempotencyKey": idempotency_key})
        return bool(self._request(ops.DELETE_TEAM, variables))

    def set_policy(
        self, input: inputs.SetTeamPolicyInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Set who may create teams in the app and new teams' default membership policy.

        App-admin (``manage_apps``). It applies to teams created from now on; existing ones
        are unchanged. A ``max_members`` or ``max_groups_per_user`` of ``None`` means
        unlimited.
        """
        result: dict[str, Any] = self._request(ops.SET_TEAM_POLICY, {"input": input})
        return result

    def join(self, group_id: str | int) -> dict[str, Any]:
        """Join a team as the caller, as its membership policy allows. No permission needed.

        ``open`` admits at once; ``request`` leaves the membership ``pending`` until a
        manager approves; ``invite`` and ``admin`` refuse, as does a ban (``FORBIDDEN``).
        The returned member's ``status`` says which.
        """
        result: dict[str, Any] = self._request(ops.JOIN_TEAM, {"groupId": bigint(group_id)})
        return result

    def request_to_join(self, group_id: str | int) -> dict[str, Any]:
        """Ask to join a request-only team; the pending membership waits for :meth:`add_member`.

        It behaves exactly as :meth:`join`, named for request-policy UIs.
        """
        result: dict[str, Any] = self._request(
            ops.REQUEST_TO_JOIN_TEAM, {"groupId": bigint(group_id)}
        )
        return result

    def leave(self, group_id: str | int, idempotency_key: str | None = None) -> bool:
        """Leave a team. ``True`` if a membership was removed, ``False`` if the caller had none.

        ``idempotency_key`` makes a retry safe: the same key with the same ``group_id``
        answers the first result, with another ``group_id`` it raises
        ``IDEMPOTENCY_CONFLICT``. Keys expire after 24 hours.
        """
        variables = omit_none({"groupId": bigint(group_id), "idempotencyKey": idempotency_key})
        return bool(self._request(ops.LEAVE_TEAM, variables))

    def add_member(self, group_id: str | int, user_id: str | int) -> dict[str, Any]:
        """Add a user to a team, or approve their pending request. Needs ``manage_members``.

        The membership becomes ``active``, with the team's default role when one is
        configured.
        """
        result: dict[str, Any] = self._request(
            ops.ADD_TEAM_MEMBER, {"groupId": bigint(group_id), "userId": bigint(user_id)}
        )
        return result

    def remove_member(self, group_id: str | int, user_id: str | int) -> bool:
        """Remove a member from a team, with their roles. ``True`` if a membership was removed.

        Needs ``manage_members``, except that any member may remove themselves (pass your
        own ``user_id``).
        """
        return bool(
            self._request(
                ops.REMOVE_TEAM_MEMBER, {"groupId": bigint(group_id), "userId": bigint(user_id)}
            )
        )

    def set_member_roles(
        self, input: inputs.SetMemberRolesInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Replace a member's team roles with ``role_ids``. Needs ``manage_roles``.

        Not additive: roles left out are removed, and ids that are unknown or belong to
        another group are ignored.
        """
        result: dict[str, Any] = self._request(ops.SET_TEAM_MEMBER_ROLES, {"input": input})
        return result

    def create_role(
        self, input: inputs.CreateGroupRoleInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Create a custom team role granting team permission keys. Needs ``manage_roles``.

        Keys are team permission keys such as ``manage_members``, ``manage_roles`` and
        ``manage_group``, each at most 64 characters. ``role_name`` is at most 128 characters
        and unique in the team; ``rank`` (higher is more senior) defaults to 0. Raises
        ``BAD_USER_INPUT`` on a bad or taken name or an unknown key.
        """
        result: dict[str, Any] = self._request(ops.CREATE_TEAM_ROLE, {"input": input})
        return result

    def update_role(
        self, input: inputs.UpdateGroupRoleInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Change a team role's name, rank and/or permission keys. Needs ``manage_roles``.

        ``permissions`` replaces the role's keys; fields left out stay. System roles cannot
        be renamed or re-ranked.
        """
        result: dict[str, Any] = self._request(ops.UPDATE_TEAM_ROLE, {"input": input})
        return result

    def delete_role(self, group_role_id: str | int) -> bool:
        """Delete a custom team role, taking it from every member. Needs ``manage_roles``.

        The grid access the role granted is recomputed. The system ``leader`` role cannot be
        deleted (``BAD_USER_INPUT``). ``True`` if a role was deleted.
        """
        return bool(
            self._request(ops.DELETE_TEAM_ROLE, {"groupRoleId": bigint(group_role_id)})
        )
