# GENERATED by scripts/unasync.py from src/crowdypy/domains/teleport.py. Do not edit.
"""Teleport authorization (``client.teleport``).

This only *authorizes* a teleport; the replication runtime performs the move. It needs a
bearer token (``UNAUTHENTICATED`` without one) and the app's ``teleport`` runtime permission,
and reports a refusal in the answer (``success`` / ``errorCode``) rather than raising.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain

__all__ = ["TeleportAPI"]


class TeleportAPI(Domain):
    def request(
        self, input: inputs.TeleportRequestInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Whether the caller may teleport the actor ``uuid`` to a destination in an app.

        ``chunkAddress`` is int64 decimal strings, ``voxelAddress`` signed 16-bit ints and
        ``uuid`` exactly 32 ASCII characters. ``errorCode`` is ``NO_ERROR`` when allowed,
        ``INVALID_APP_ID`` for a non-positive ``appId``, and ``UNAUTHORIZED`` for the reserved
        destination ``(-6, -6, -6)`` or without the permission.
        """
        result: dict[str, Any] = self._request(ops.TELEPORT_REQUEST, {"input": input})
        return result
