# GENERATED by scripts/unasync.py from src/crowdypy/domains/udp.py. Do not edit.
"""Native UDP replication for one game client (``client.udp``).

CrowdyJS's ``client.udp`` sends through a server-side proxy because a page cannot open a UDP
socket. CrowdyPy's is CrowdyCPP's native client: the same methods (snake_case), signed
datagrams straight to the replication server the Game API assigns, notifications drained in
batches. Defaults per message type are CrowdyJS's: actor updates replicate 8 chunks with
exponential decay, voxel, text and event messages 8 chunks with none, audio and video 1.

Payloads are bytes, not base64. Sends return the message's sequence number (0-255); the
``*_and_wait`` forms wait for its echo (only actor and voxel updates echo) or a server error
naming it, as in CrowdyJS.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from typing import TYPE_CHECKING, Any, NamedTuple

from crowdypy._sync.domains.portal import AppTokenResponse, CurrentServer
from crowdypy.errors import CrowdyError, CrowdyReplicationError
from crowdypy.replication import (
    HANDLER_NAMES,
    Assignment,
    ReplicationConnection,
    ConnState,
    Notification,
    TokenMaterial,
    token_material,
)
from crowdypy.wire import DecayRate
from crowdypy.domains.udp import ConnectionStatus  # one class in both clients

if TYPE_CHECKING:
    from crowdypy._sync.client import CrowdyClient

__all__ = ["ConnectionStatus", "UdpAPI"]

_LIVE = (ConnState.CONNECTING, ConnState.CONNECTED, ConnState.RECONNECTING)




class _GameSessionProvider:
    """Assignment and refresh through the game client's own Game API calls."""

    def __init__(self, client: CrowdyClient, app_id: str) -> None:
        self._client = client
        self._app_id = app_id

    def assign_server(self) -> Assignment:
        try:
            return self._assign_once()
        except CrowdyError:
            # Assignment goes through the API client, so a failure here often means the
            # instance it is pinned to went away; only a move can recover from that.
            if not self._client.rediscover_endpoint(self._app_id):
                raise
            return self._assign_once()

    def _assign_once(self) -> Assignment:
        server = self._client.server_status.server_with_least_clients()
        if (
            not server
            or not server.get("clientPort")
            or not (server.get("ip4") or server.get("ip6"))
        ):
            raise CrowdyReplicationError("no replication server was assigned", code="Rejected")
        return Assignment(
            server.get("ip4") or "", server.get("ip6") or "", int(server["clientPort"])
        )

    def refresh_token(self, current: Assignment | None) -> TokenMaterial:
        # Naming the server the client is on gets the new token installed there, so the
        # connection keeps its socket instead of being placed again.
        server = (
            CurrentServer(ip4=current.ip4, client_port=current.client_port)
            if current is not None and current.ip4 and current.client_port > 0
            else None
        )
        token = self._client.portal.refresh(server)
        self._client.app_token = token
        return token_material(token, current)


class UdpAPI:
    def __init__(self, client: CrowdyClient) -> None:
        self._client = client
        self._connection: ReplicationConnection | None = None
        self._subscriptions: list[Mapping[str, Callable[[Notification], Any]]] = []

    @property
    def connection(self) -> ReplicationConnection | None:
        """The native connection, once :meth:`connect` made one: batches, stats, batch sends."""
        return self._connection

    def connect(
        self, app_token: AppTokenResponse | None = None, **options: Any
    ) -> ConnectionStatus:
        """Assign a replication server and open the socket. Idempotent while connected.

        ``app_token`` is the minted (or refreshed) token for the app; without it the client's
        :attr:`~crowdypy.CrowdyClient.app_token` is used. ``options`` tune the native
        connection (``bundle_window_ms``, ``ring_capacity``, ``manual_pump``, ...).
        """
        if self._connection is not None and self._connection.state in _LIVE:
            return self.connection_status()
        token = app_token or self._client.app_token
        if token is None:
            raise CrowdyReplicationError(
                "connect needs the app token: pass the AppTokenResponse from "
                "portal.mint_app_token, or call client.set_app_token() first",
                code="NotConnected",
            )
        if app_token is not None:
            self._client.set_app_token(app_token)
        if self._connection is None or options:
            if self._connection is not None:
                self._connection.close()
            self._connection = ReplicationConnection(
                _GameSessionProvider(self._client, token.app_id),
                token_material(token),
                app_id=token.app_id,
                subscriptions=self._subscriptions,
                **options,
            )
        else:
            self._connection.set_token(token_material(token))
        self._connection.connect()
        return self.connection_status()

    def disconnect(self) -> bool:
        """Close the socket and release the connection; subscriptions are kept for the next one."""
        connection, self._connection = self._connection, None
        if connection is not None:
            connection.close()
        return True

    def connection_status(self) -> ConnectionStatus:
        connection = self._connection
        if connection is None:
            return ConnectionStatus(False, ConnState.IDLE)
        state = connection.state
        if state not in _LIVE:
            return ConnectionStatus(False, state)
        server = connection.assignment()
        return ConnectionStatus(
            state == ConnState.CONNECTED,
            state,
            server.ip4 or None,
            server.ip6 or None,
            server.client_port or None,
        )

    def flush_sends(self) -> None:
        """Put the pending bundle on the wire now (at the end of a frame)."""
        if self._connection is not None:
            self._connection.flush_sends()

    def wait_for_in_flight_actor_updates(self) -> None:
        """Native sends complete when they return; this only flushes the pending bundle."""
        self.flush_sends()

    def subscribe(
        self, handlers: Mapping[str, Callable[[Notification], Any]]
    ) -> Callable[[], None]:
        """Call ``handlers[name](notification)`` per event (names in
        :data:`crowdypy.replication.HANDLER_NAMES`); kept across reconnects. Returns the
        unsubscribe function. On a hot path read ``connection.batches()`` instead."""
        unknown = set(handlers) - HANDLER_NAMES
        if unknown:
            raise ValueError(f"unknown handler name(s): {', '.join(sorted(unknown))}")
        entry = dict(handlers)
        self._subscriptions.append(entry)

        def unsubscribe() -> None:
            if entry in self._subscriptions:
                self._subscriptions.remove(entry)

        return unsubscribe

    def _live(self) -> ReplicationConnection:
        connection = self._connection
        if connection is None:
            raise CrowdyReplicationError("call client.udp.connect() first", code="NotConnected")
        return connection

    # ----- sends

    def send_actor_update(
        self,
        chunk: Sequence[int],
        uuid: str,
        state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.EXPONENTIAL,
    ) -> int:
        return self._live().send_actor_update(chunk, uuid, state, distance=distance, decay=decay)

    def send_actor_update_and_wait(
        self,
        chunk: Sequence[int],
        uuid: str,
        state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.EXPONENTIAL,
        timeout: float = 5.0,
    ) -> Notification:
        connection = self._live()
        sequence = connection.send_actor_update(chunk, uuid, state, distance=distance, decay=decay)
        connection.flush_sends()
        return connection.wait_for_sequence(sequence, uuid, timeout)

    def send_voxel_update(
        self,
        chunk: Sequence[int],
        uuid: str,
        voxel: Sequence[int],
        voxel_type: int,
        voxel_state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
    ) -> int:
        return self._live().send_voxel_update(
            chunk, uuid, voxel, voxel_type, voxel_state, distance=distance, decay=decay
        )

    def send_voxel_update_and_wait(
        self,
        chunk: Sequence[int],
        uuid: str,
        voxel: Sequence[int],
        voxel_type: int,
        voxel_state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
        timeout: float = 5.0,
    ) -> Notification:
        connection = self._live()
        sequence = connection.send_voxel_update(
            chunk, uuid, voxel, voxel_type, voxel_state, distance=distance, decay=decay
        )
        connection.flush_sends()
        return connection.wait_for_sequence(sequence, uuid, timeout)

    def send_audio_packet(
        self,
        chunk: Sequence[int],
        uuid: str,
        audio: Any,
        *,
        distance: int = 1,
        decay: int = DecayRate.NONE,
    ) -> int:
        return self._live().send_audio_packet(chunk, uuid, audio, distance=distance, decay=decay)

    def send_audio_packet_and_wait(
        self,
        chunk: Sequence[int],
        uuid: str,
        audio: Any,
        *,
        distance: int = 1,
        decay: int = DecayRate.NONE,
        timeout: float = 5.0,
    ) -> Notification:
        """Audio is never echoed: this surfaces a server error inline, and otherwise times out
        (``UDP_SEQUENCE_TIMEOUT``), as in CrowdyJS."""
        connection = self._live()
        sequence = connection.send_audio_packet(chunk, uuid, audio, distance=distance, decay=decay)
        connection.flush_sends()
        return connection.wait_for_sequence(sequence, uuid, timeout)

    def send_video_packet(
        self,
        chunk: Sequence[int],
        uuid: str,
        fragment: Any,
        *,
        distance: int = 1,
        decay: int = DecayRate.NONE,
    ) -> int:
        return self._live().send_video_packet(chunk, uuid, fragment, distance=distance, decay=decay)

    def send_video_frame(
        self,
        chunk: Sequence[int],
        uuid: str,
        frame: Any,
        frame_id: int,
        *,
        codec: int = 0,
        distance: int = 1,
        decay: int = DecayRate.NONE,
    ) -> int:
        """Fragment one encoded frame and send every fragment; returns how many were sent."""
        return self._live().send_video_frame(
            chunk, uuid, frame, frame_id, codec=codec, distance=distance, decay=decay
        )

    def send_text_packet(
        self,
        chunk: Sequence[int],
        uuid: str,
        text: str | bytes,
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
    ) -> int:
        return self._live().send_text_packet(chunk, uuid, text, distance=distance, decay=decay)

    def send_text_packet_and_wait(
        self,
        chunk: Sequence[int],
        uuid: str,
        text: str | bytes,
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
        timeout: float = 5.0,
    ) -> Notification:
        """Text is never echoed: see :meth:`send_audio_packet_and_wait`."""
        connection = self._live()
        sequence = connection.send_text_packet(chunk, uuid, text, distance=distance, decay=decay)
        connection.flush_sends()
        return connection.wait_for_sequence(sequence, uuid, timeout)

    def send_client_event(
        self,
        chunk: Sequence[int],
        uuid: str,
        event_type: int,
        state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
    ) -> int:
        return self._live().send_client_event(
            chunk, uuid, event_type, state, distance=distance, decay=decay
        )

    def send_client_event_and_wait(
        self,
        chunk: Sequence[int],
        uuid: str,
        event_type: int,
        state: Any = b"",
        *,
        distance: int = 8,
        decay: int = DecayRate.NONE,
        timeout: float = 5.0,
    ) -> Notification:
        """Events are never echoed: see :meth:`send_audio_packet_and_wait`."""
        connection = self._live()
        sequence = connection.send_client_event(
            chunk, uuid, event_type, state, distance=distance, decay=decay
        )
        connection.flush_sends()
        return connection.wait_for_sequence(sequence, uuid, timeout)

    def send_single_actor_message(self, chunk: Sequence[int], uuid: str, payload: Any) -> int:
        """A direct message to one actor: ``chunk`` and ``uuid`` address the TARGET. Not echoed."""
        return self._live().send_single_actor_message(chunk, uuid, payload)

    def send_channel_message(self, channel_id: str | int, uuid: str, payload: Any) -> int:
        """Publish to a channel (needs membership and ``send_messages``)."""
        return self._live().send_channel_message(channel_id, uuid, payload)
