# GENERATED by scripts/unasync.py from src/crowdypy/domains/voxels.py. Do not edit.
"""Voxel edits: the edit log, its history and rollback (``client.voxels``).

A voxel edit is one row of an app's edit log: the chunk and local position that changed, the
new voxel type, an optional base64 ``state`` blob, and who made it when. A background job
later folds edits into the chunk's packed grid (:class:`~crowdypy.domains.chunks.ChunksAPI`).
Use this for authoritative reads, audit history and rollback; realtime edits are far cheaper
over the UDP replication path.

Chunk coordinates are int64 decimal strings, voxel positions 0-15 per axis, and ``appId`` /
``userId`` BigInt decimal strings. Every call needs a bearer token, and an app-scoped token
reaches only its own app (``UNAUTHENTICATED`` / ``FORBIDDEN``).
"""

from __future__ import annotations

import builtins  # VoxelsAPI.list shadows the builtin in the class's annotations
from collections.abc import Mapping
from typing import Any

from crowdypy._generated import inputs
from crowdypy._generated import operations as ops
from crowdypy._sync.domains._base import Domain, omit_none
from crowdypy.utils import bigint

__all__ = ["VoxelsAPI"]


class VoxelsAPI(Domain):
    def list(
        self, input: inputs.ListVoxelsInput | Mapping[str, Any]
    ) -> builtins.list[dict[str, Any]]:
        """The recorded edits of one chunk, newest first; ``since`` keeps those at or after it.

        Read-only.
        """
        result: builtins.list[dict[str, Any]] = self._request(
            ops.LIST_VOXELS, {"input": input}
        )
        return result

    def list_by_distance(
        self, input: inputs.ListVoxelUpdatesByDistanceInput | Mapping[str, Any]
    ) -> dict[str, Any]:
        """Recorded edits of every chunk within ``maxDistance`` chunks (1-8) of a center chunk.

        Grouped per chunk by increasing distance and paginated over chunks, not voxels
        (``limit`` default 1000, ``skip``); ``since`` bounds the edits. ``BAD_USER_INPUT`` for
        a ``maxDistance`` outside 1-8. Read-only.
        """
        result: dict[str, Any] = self._request(
            ops.LIST_VOXEL_UPDATES_BY_DISTANCE, {"input": input}
        )
        return result

    def update(self, input: inputs.UpdateVoxelInput | Mapping[str, Any]) -> dict[str, Any]:
        """Record (upsert) one voxel edit; a background job folds it into the chunk's grid.

        Writes world state. ``location`` is 0-15 per axis and ``voxelType`` 0-255. Needs active
        app access and ``update_voxel_data`` (on a covering grid too, where grids cover the
        chunk), and is refused while the app's wilderness is closed for a chunk only its world
        grid covers (``SCOPE_MISSING`` / ``FORBIDDEN``).
        """
        result: dict[str, Any] = self._request(ops.UPDATE_VOXEL, {"input": input})
        return result

    def history(
        self,
        app_id: str | int,
        *,
        user_id: str | int | None = None,
        from_: str | None = None,
        to: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> builtins.list[dict[str, Any]]:
        """The app's immutable voxel edit history, newest first.

        Filter by ``user_id`` and an inclusive ISO-8601 ``from_`` / ``to`` window. ``limit``
        (default 500, 1-50000) and ``offset`` are deprecated offset paging: prefer
        :meth:`history_connection` for a large history. Read-only.
        """
        variables = omit_none(
            {
                "appId": bigint(app_id),
                "userId": bigint(user_id) if user_id is not None else None,
                "from": from_,
                "to": to,
                "limit": limit,
                "offset": offset,
            }
        )
        result: builtins.list[dict[str, Any]] = self._request(
            ops.VOXEL_UPDATE_HISTORY, variables
        )
        return result

    def history_connection(
        self,
        app_id: str | int,
        *,
        user_id: str | int | None = None,
        from_: str | None = None,
        to: str | None = None,
        first: int | None = None,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Cursor-paginated :meth:`history`: ``edges { cursor node }``, ``pageInfo``, ``totalCount``.

        Page with ``first`` (default 50, max 200) and the previous page's
        ``pageInfo.endCursor`` as ``after``; the filters are :meth:`history`'s. Read-only.
        """
        variables = omit_none(
            {
                "appId": bigint(app_id),
                "userId": bigint(user_id) if user_id is not None else None,
                "from": from_,
                "to": to,
                "first": first,
                "after": after,
            }
        )
        result: dict[str, Any] = self._request(ops.VOXEL_UPDATE_HISTORY_CONNECTION, variables)
        return result

    def rollback(
        self, input: inputs.RollbackVoxelUpdatesInput | Mapping[str, Any]
    ) -> builtins.list[dict[str, Any]]:
        """Revert every edit ``userId`` made in ``appId`` between ``from`` and ``to``.

        A dry run unless ``dryRun`` is false: one result per affected voxel, nothing written,
        and ``applied`` true only for an edit actually reverted. Needs ``manage_apps`` on the
        org that owns the app (``SCOPE_MISSING`` / ``FORBIDDEN``). The idempotency key is a
        field of the input (``idempotencyKey``): the same key with identical input replays
        the first result, with different input it is ``IDEMPOTENCY_CONFLICT``; keys expire
        after 24 hours.
        """
        result: builtins.list[dict[str, Any]] = self._request(
            ops.ROLLBACK_VOXEL_UPDATES, {"input": input}
        )
        return result
