# GENERATED by scripts/unasync.py from src/crowdypy/graphql.py. Do not edit.
"""The GraphQL HTTP transport.

One endpoint, one token read fresh from the session on every request, the sticky
load-balancer cookie, a timeout, and every failure normalized into a typed
:class:`~crowdypy.errors.CrowdyError`.

This module is the async source; ``crowdypy._sync.graphql`` is generated from it by
``scripts/unasync.py``. Write it so that removing ``async``/``await`` yields correct
blocking code.
"""

from __future__ import annotations

import logging
from collections.abc import Callable, Mapping
from http.cookiejar import CookieJar, DefaultCookiePolicy
from typing import Any

import httpx
import msgspec

from crowdypy._default_origin import CROWDY_DEFAULT_HTTP_ORIGIN
from crowdypy._operation import Operation
from crowdypy._version import __version__
from crowdypy.datacenter_redirect import DatacenterMove, move_from_errors
from crowdypy.errors import (
    APP_UNAVAILABLE_CODE,
    CrowdyAppUnavailableError,
    CrowdyGraphQLError,
    CrowdyHttpError,
    CrowdyNetworkError,
    CrowdyTimeoutError,
    CrowdyUserCodeFaultError,
)
from crowdypy.lb_cookie import LbCookieStore
from crowdypy.session import SessionStore

__all__ = ["GraphQLClient", "WrongDatacenterHandler", "graphql_endpoint"]

WrongDatacenterHandler = Callable[[DatacenterMove], bool]

_USER_AGENT = f"crowdypy/{__version__}"
_JSON_DECODER = msgspec.json.Decoder()
_JSON_ENCODER = msgspec.json.Encoder()


def graphql_endpoint(url: str | None, suffix: str = "graphql") -> str | None:
    """``https://host`` and ``https://host/graphql`` both become ``https://host/graphql``."""
    if url is None or not url.strip():
        return None
    trimmed = url.strip().rstrip("/")
    return trimmed if trimmed.endswith(f"/{suffix}") else f"{trimmed}/{suffix}"


def _no_cookie_jar() -> CookieJar:
    # httpx would otherwise remember every Set-Cookie and replay it. The only cookie
    # this SDK carries is the LB pin, sent explicitly so the realtime socket can send
    # the identical value.
    return CookieJar(policy=DefaultCookiePolicy(allowed_domains=[]))


def _raise_for_errors(errors: list[Mapping[str, Any]]) -> None:
    # Subclasses rather than codes to remember: every existing `except
    # CrowdyGraphQLError` keeps working, and only code that wants to tell "your app is
    # offline" or "the app's own code failed" apart has to look further.
    if any((e.get("extensions") or {}).get("code") == APP_UNAVAILABLE_CODE for e in errors):
        raise CrowdyAppUnavailableError(errors)
    if any(isinstance((e.get("extensions") or {}).get("blame"), str) for e in errors):
        raise CrowdyUserCodeFaultError(errors)
    raise CrowdyGraphQLError(errors)


class GraphQLClient:
    """POSTs operations to one endpoint and returns their ``data``.

    Most callers use the typed sub-clients on the client; ``client.graphql`` is the
    escape hatch for a field no sub-client wraps yet.
    """

    def __init__(
        self,
        session: SessionStore,
        *,
        endpoint: str | None = None,
        timeout: float = 60.0,
        logger: logging.Logger | None = None,
        lb_cookie_store: LbCookieStore | None = None,
        http_client: httpx.Client | None = None,
        on_wrong_datacenter: WrongDatacenterHandler | None = None,
    ) -> None:
        # The last resort is the tier's PUBLIC origin from the generated default, never
        # localhost: an unconfigured client should reach the real API, not "connection
        # refused" against its own machine.
        self._endpoint = endpoint or f"{CROWDY_DEFAULT_HTTP_ORIGIN}/graphql"
        self._timeout = timeout
        self._session = session
        self._logger = logger or logging.getLogger("crowdypy")
        self._lb_cookie_store = lb_cookie_store
        self._owns_http = http_client is None
        self._http = http_client or httpx.Client(cookies=_no_cookie_jar())
        self._on_wrong_datacenter = on_wrong_datacenter

    @property
    def endpoint(self) -> str:
        return self._endpoint

    def get_endpoint(self) -> str:
        return self._endpoint

    def set_endpoint(self, endpoint: str) -> None:
        """Point later requests at another instance (direct connect re-discovery)."""
        self._endpoint = endpoint

    def set_wrong_datacenter_handler(self, handler: WrongDatacenterHandler | None) -> None:
        self._on_wrong_datacenter = handler

    def request(
        self, operation: Operation, variables: Mapping[str, Any] | None = None
    ) -> dict[str, Any]:
        """Send one generated (or inline) operation and return its ``data``."""
        result: dict[str, Any] = self.query(
            operation.document, variables, operation_name=operation.name
        )
        return result

    def query(
        self,
        document: str,
        variables: Mapping[str, Any] | None = None,
        *,
        operation_name: str | None = None,
    ) -> Any:
        """Send a raw GraphQL document. Prefer :meth:`request` with an :class:`Operation`."""
        try:
            return self._attempt(document, variables, operation_name)
        except CrowdyGraphQLError as error:
            move = move_from_errors(error.graphql_errors)
            if move is None or self._on_wrong_datacenter is None:
                raise
            # ONE retry, and only after the endpoint actually moved. Without the retry
            # every call fails once and the application has to repeat it; without the
            # "actually moved" check a declined or no-op move re-sends to the same
            # instance and is refused identically, forever. A second WRONG_DATACENTER
            # after a real move is a placement problem for an operator, not a loop.
            try:
                moved = self._on_wrong_datacenter(move) is True
            except Exception:
                self._logger.warning(
                    "datacenter redirect handler failed; surfacing the original error",
                    exc_info=True,
                )
                raise error from None
            if not moved:
                raise
            self._logger.info(
                "moved to %s at %s and retrying",
                move.app_datacenter or "the app's datacenter",
                move.game_api_url,
            )
            return self._attempt(document, variables, operation_name)

    def prime_lb_cookie(self) -> None:
        """Ask the load balancer for its pin before opening a realtime socket."""
        if self._lb_cookie_store is None or self._lb_cookie_store.get_value():
            return
        self._attempt("{ __typename }", None, None)

    def _attempt(
        self, document: str, variables: Mapping[str, Any] | None, operation_name: str | None
    ) -> Any:
        headers = {"Content-Type": "application/json", "User-Agent": _USER_AGENT}
        token = self._session.get_token()
        if token:
            headers["Authorization"] = f"Bearer {token}"
        lb_cookie = self._lb_cookie_store.header_value() if self._lb_cookie_store else None
        if lb_cookie:
            headers["Cookie"] = lb_cookie
        body: dict[str, Any] = {"query": document, "variables": dict(variables or {})}
        if operation_name:
            body["operationName"] = operation_name
        try:
            response = self._http.post(
                self._endpoint,
                content=_JSON_ENCODER.encode(body),
                headers=headers,
                timeout=self._timeout,
            )
        except httpx.TimeoutException as exc:
            raise CrowdyTimeoutError(self._timeout * 1000) from exc
        except httpx.HTTPError as exc:
            raise CrowdyNetworkError(exc) from exc
        if self._lb_cookie_store is not None:
            self._lb_cookie_store.ingest_set_cookie(response.headers.get_list("set-cookie"))
        if response.status_code < 200 or response.status_code >= 300:
            raise CrowdyHttpError(response.status_code, response.text)
        try:
            result = _JSON_DECODER.decode(response.content)
        except msgspec.DecodeError as exc:
            raise CrowdyNetworkError(exc) from exc
        if not isinstance(result, dict):
            raise CrowdyNetworkError(f"unexpected GraphQL response: {type(result).__name__}")
        errors = result.get("errors")
        if errors:
            _raise_for_errors(errors)
        return result.get("data")

    def close(self) -> None:
        if self._owns_http:
            self._http.close()

    def __enter__(self) -> GraphQLClient:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()
