# GENERATED by scripts/unasync.py from src/crowdypy/grid_scope.py. Do not edit.
"""One grid, bound once: ``client.grid(app_id, grid_id)``.

Grid scope is app scope intersected with grid confinement. Each method is the ordinary call
with the app and grid filled in and, where the call addresses the world, a local check that
it stays inside the grid. The check is for the caller's benefit: the server enforces the same
rule for grid tokens, and grid-owner rules for everyone.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING, Any

from crowdypy._grid import GridBox, chunk_coords
from crowdypy.errors import GridScopeError

if TYPE_CHECKING:
    from collections.abc import Sequence

    from crowdypy._sync.domains.channels import ChannelsAPI
    from crowdypy._sync.domains.grids import GridsAPI
    from crowdypy._sync.domains.udp import UdpAPI

__all__ = ["GridChannels", "GridScope", "GridSends"]


class GridScope:
    """One grid of one app. The box is learned from the first grid token minted, or passed in."""

    def __init__(
        self,
        grids: GridsAPI,
        channels: ChannelsAPI,
        app_id: str | int,
        grid_id: str | int,
        box: GridBox | None = None,
        udp: UdpAPI | None = None,
    ) -> None:
        self.app_id = str(app_id)
        self.grid_id = str(grid_id)
        self._grids = grids
        self._box = box
        #: Grid channels: the only channels this grid's modules may post into.
        self.channels = GridChannels(self, grids, channels, udp)
        #: Replication that originates in the grid, on ``client.udp``.
        self.send = GridSends(self, udp)

    @property
    def bounds(self) -> GridBox | None:
        """The grid box, once known (after :meth:`mint_token`, or when passed in)."""
        return self._box

    def contains(self, chunk: Any) -> bool:
        """Whether a chunk is inside the grid. ``False`` while the box is unknown."""
        return self._box is not None and self._box.contains(chunk)

    def assert_contains(self, chunk: Any) -> None:
        """Raise :class:`GridScopeError` unless the chunk is inside the (known) grid box."""
        if self._box is None:
            raise GridScopeError(
                "grid box unknown: call mint_token() first or pass the box to client.grid()"
            )
        if not self._box.contains(chunk):
            x, y, z = chunk_coords(chunk)
            raise GridScopeError(f"chunk ({x},{y},{z}) is outside grid {self.grid_id}")

    def mint_token(self, ttl_seconds: int | None = None) -> dict[str, Any]:
        """Mint a grid-scoped token for this grid, and learn the box from it."""
        request: dict[str, Any] = {"appId": self.app_id, "gridId": self.grid_id}
        if ttl_seconds is not None:
            request["ttlSeconds"] = ttl_seconds
        token = self._grids.mint_token(request)
        self._box = GridBox(chunk_coords(token["lowChunk"]), chunk_coords(token["highChunk"]))
        return token


class GridChannels:
    """The channels of one grid (``scope.channels``)."""

    def __init__(
        self, scope: GridScope, grids: GridsAPI, channels: ChannelsAPI, udp: UdpAPI | None
    ) -> None:
        self._scope = scope
        self._grids = grids
        self._channels = channels
        self._udp = udp

    def list(self) -> builtins.list[dict[str, Any]]:
        return self._grids.channels(self._scope.app_id, self._scope.grid_id)

    def create(
        self,
        name: str,
        *,
        description: str | None = None,
        membership_policy: str | None = None,
        members_can_send: bool | None = None,
        members_can_speak: bool | None = None,
    ) -> dict[str, Any]:
        """``members_can_speak`` gives the default member role ``send_voice`` (channel
        audio)."""
        request: dict[str, Any] = {
            "appId": self._scope.app_id,
            "gridId": self._scope.grid_id,
            "name": name,
        }
        if description is not None:
            request["description"] = description
        if membership_policy is not None:
            request["membershipPolicy"] = membership_policy
        if members_can_send is not None:
            request["membersCanSend"] = members_can_send
        if members_can_speak is not None:
            request["membersCanSpeak"] = members_can_speak
        return self._grids.create_channel(request)

    def join(self, channel_id: str | int) -> dict[str, Any]:
        return self._channels.join(channel_id)

    def leave(self, channel_id: str | int) -> bool:
        return self._channels.leave(channel_id)

    def send(self, channel_id: str | int, uuid: str, payload: Any) -> int:
        """Publish to one of the grid's channels over ``client.udp``; returns the sequence."""
        return _udp(self._udp).send_channel_message(channel_id, uuid, payload)

    def send_audio(self, channel_id: str | int, uuid: str, payload: Any) -> int:
        """Channel audio over ``client.udp``: needs ``send_voice`` on the channel and the
        player's ``use_voice_chat``. Returns the sequence."""
        return _udp(self._udp).send_channel_audio(channel_id, uuid, payload)


class GridSends:
    """Each send checks its chunk against the grid box, then goes out as the ordinary
    ``client.udp`` send; how far it replicates still follows ``distance``."""

    def __init__(self, scope: GridScope, udp: UdpAPI | None) -> None:
        self._scope = scope
        self._udp = udp

    def actor_update(
        self, chunk: Sequence[int], uuid: str, state: Any = b"", **options: Any
    ) -> int:
        self._scope.assert_contains(chunk)
        return _udp(self._udp).send_actor_update(chunk, uuid, state, **options)

    def voxel_update(
        self,
        chunk: Sequence[int],
        uuid: str,
        voxel: Sequence[int],
        voxel_type: int,
        voxel_state: Any = b"",
        **options: Any,
    ) -> int:
        self._scope.assert_contains(chunk)
        return _udp(self._udp).send_voxel_update(
            chunk, uuid, voxel, voxel_type, voxel_state, **options
        )

    def text(self, chunk: Sequence[int], uuid: str, text: str | bytes, **options: Any) -> int:
        self._scope.assert_contains(chunk)
        return _udp(self._udp).send_text_packet(chunk, uuid, text, **options)

    def client_event(
        self, chunk: Sequence[int], uuid: str, event_type: int, state: Any = b"", **options: Any
    ) -> int:
        self._scope.assert_contains(chunk)
        return _udp(self._udp).send_client_event(chunk, uuid, event_type, state, **options)


def _udp(udp: UdpAPI | None) -> UdpAPI:
    if udp is None:
        raise GridScopeError("this grid scope has no replication connection: use client.grid()")
    return udp
