# GENERATED by scripts/unasync.py from src/crowdypy/rediscover.py. Do not edit.
"""Finding another endpoint when the one a client holds has stopped answering.

Under direct connect ``game_api_url`` names ONE API instance. When it goes away,
retrying its hostname cannot recover; re-discovery asks something that does not die
with it (the shared discovery origin, or a fresh mint) where to go instead.

Async source; ``crowdypy._sync.rediscover`` is generated from it.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol

import httpx
import msgspec

from crowdypy._sync.graphql import graphql_endpoint

__all__ = [
    "BOOTSTRAP_QUERY",
    "Endpoint",
    "MintCapablePortal",
    "RediscoverFn",
    "create_bootstrap_rediscover",
    "create_mint_rediscover",
]

BOOTSTRAP_QUERY = (
    "query CrowdyPyRediscover($appId: BigInt!) {\n"
    "  gameClientBootstrap(appId: $appId) { gameApiUrl gameApiWsUrl discoveryUrl }\n"
    "}"
)


@dataclass(frozen=True, slots=True)
class Endpoint:
    """A re-discovery answer. A ``None`` field means no answer for it, not "clear it"."""

    http_url: str | None
    ws_url: str | None


class RediscoverFn(Protocol):
    """Given the app being played (or ``None``), where should the client go?

    Must not raise: ``None`` leaves the client where it is, with its ordinary retry.
    """

    def __call__(self, app_id: str | None) -> Endpoint | None: ...


class MintCapablePortal(Protocol):
    def mint_app_token(self, app_id: str | int) -> Any: ...


def create_mint_rediscover(
    portal: MintCapablePortal,
    *,
    app_id: str | None = None,
    logger: logging.Logger | None = None,
) -> RediscoverFn:
    """Re-discover by minting a fresh app token on an identity client."""
    log = logger or logging.getLogger("crowdypy")
    pinned_app_id = app_id

    def rediscover(app_id: str | None) -> Endpoint | None:
        target = pinned_app_id or app_id
        if not target:
            log.warning("Cannot re-discover: no app id. Pass one to create_mint_rediscover.")
            return None
        try:
            minted = portal.mint_app_token(target)
        except Exception as exc:  # re-discovery must never raise into a reconnect path
            log.warning("Re-discovery via mint_app_token failed: %s", exc)
            return None
        return Endpoint(http_url=minted.game_api_url, ws_url=minted.game_api_ws_url)

    return rediscover


def create_bootstrap_rediscover(
    discovery_url: str,
    get_token: Callable[[], str | None],
    *,
    app_id: str | None = None,
    http_client: httpx.Client | None = None,
    timeout: float = 10.0,
    logger: logging.Logger | None = None,
) -> RediscoverFn:
    """Re-discover by asking the discovery origin's ``gameClientBootstrap``.

    ``discovery_url`` must be the load balancer (``mint_app_token``'s ``discovery_url``),
    never the instance it exists to replace.
    """
    log = logger or logging.getLogger("crowdypy")
    endpoint = graphql_endpoint(discovery_url) or discovery_url
    pinned_app_id = app_id

    def rediscover(app_id: str | None) -> Endpoint | None:
        target = pinned_app_id or app_id
        if not target:
            log.warning("Cannot re-discover: no app id. Pass one to create_bootstrap_rediscover.")
            return None
        headers = {"Content-Type": "application/json"}
        token = get_token()
        if token:
            headers["Authorization"] = f"Bearer {token}"
        body = msgspec.json.encode({"query": BOOTSTRAP_QUERY, "variables": {"appId": str(target)}})
        try:
            if http_client is not None:
                response = http_client.post(
                    endpoint, content=body, headers=headers, timeout=timeout
                )
            else:
                with httpx.Client() as client:
                    response = client.post(
                        endpoint, content=body, headers=headers, timeout=timeout
                    )
            if response.status_code < 200 or response.status_code >= 300:
                log.warning("Re-discovery via discovery_url failed: HTTP %s", response.status_code)
                return None
            found = ((msgspec.json.decode(response.content) or {}).get("data") or {}).get(
                "gameClientBootstrap"
            ) or {}
        except Exception as exc:  # re-discovery must never raise into a reconnect path
            log.warning("Re-discovery via discovery_url failed: %s", exc)
            return None
        if not found.get("gameApiUrl") and not found.get("gameApiWsUrl"):
            log.warning("Re-discovery returned no endpoint.")
            return None
        return Endpoint(http_url=found.get("gameApiUrl"), ws_url=found.get("gameApiWsUrl"))

    return rediscover
