#!/usr/bin/env python3
"""Generate src/crowdypy/_generated/ from schema.gql and operations/.

    python scripts/codegen.py          # write
    python scripts/codegen.py --check  # regenerate in memory; refuse drift

Maintainer-only (needs graphql-core). A wheel or sdist build never runs this: the
generated modules are committed, and each one carries the sha256 of the inputs it was
generated from, so `--check` catches an input edited without regenerating and a
generated file edited by hand.

Every operation is isolated with exactly the fragments it reaches (transitively) and
validated against the schema, so a document the server would refuse fails here.
"""

from __future__ import annotations

import argparse
import hashlib
import keyword
import re
import sys
from pathlib import Path

from graphql import (
    DocumentNode,
    FragmentDefinitionNode,
    FragmentSpreadNode,
    GraphQLEnumType,
    GraphQLInputObjectType,
    GraphQLList,
    GraphQLNonNull,
    GraphQLScalarType,
    OperationDefinitionNode,
    Undefined,
    Visitor,
    build_schema,
    parse,
    print_ast,
    validate,
    visit,
)

from _pins import ROOT, tree_sha256

SCHEMA = ROOT / "schema.gql"
OPERATIONS = ROOT / "operations"
OUT = ROOT / "src" / "crowdypy" / "_generated"

SCALARS = {
    "ID": "str",
    "String": "str",
    "Int": "int",
    "Float": "float",
    "Boolean": "bool",
    # Decimal strings on the wire, as everywhere on the platform.
    "BigInt": "str",
    "DateTime": "str",
}


def snake(name: str) -> str:
    out = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    out = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", out)
    return out.lower()


def screaming(name: str) -> str:
    return snake(name).upper()


def py_identifier(name: str) -> str:
    return f"{name}_" if keyword.iskeyword(name) or keyword.issoftkeyword(name) else name


class _Spreads(Visitor):
    def __init__(self) -> None:
        super().__init__()
        self.names: list[str] = []

    def enter_fragment_spread(self, node: FragmentSpreadNode, *_: object) -> None:
        self.names.append(node.name.value)


def _spreads(node: object) -> list[str]:
    visitor = _Spreads()
    visit(node, visitor)  # type: ignore[arg-type]
    return visitor.names


def load_documents() -> tuple[
    list[tuple[str, OperationDefinitionNode]], dict[str, FragmentDefinitionNode]
]:
    operations: list[tuple[str, OperationDefinitionNode]] = []
    fragments: dict[str, FragmentDefinitionNode] = {}
    for path in sorted(OPERATIONS.rglob("*.graphql")):
        rel = path.relative_to(OPERATIONS).as_posix()
        document = parse(path.read_text(encoding="utf-8"))
        for definition in document.definitions:
            if isinstance(definition, OperationDefinitionNode):
                if definition.name is None:
                    raise SystemExit(f"codegen: {rel} has an anonymous operation")
                operations.append((rel, definition))
            elif isinstance(definition, FragmentDefinitionNode):
                name = definition.name.value
                if name in fragments:
                    raise SystemExit(f"codegen: fragment {name} is defined twice ({rel})")
                fragments[name] = definition
    names = [op.name.value for _, op in operations if op.name]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise SystemExit(f"codegen: operation names defined twice: {', '.join(duplicates)}")
    return operations, fragments


def isolate(
    op: OperationDefinitionNode, fragments: dict[str, FragmentDefinitionNode]
) -> DocumentNode:
    needed: list[str] = []
    queue = _spreads(op)
    while queue:
        name = queue.pop(0)
        if name in needed:
            continue
        if name not in fragments:
            raise SystemExit(
                f"codegen: {op.name.value if op.name else '?'} spreads unknown fragment {name}"
            )
        needed.append(name)
        queue.extend(_spreads(fragments[name]))
    return DocumentNode(definitions=(op, *(fragments[n] for n in sorted(needed))))


def render_operations(schema_sha: str, ops_sha: str) -> str:
    schema = build_schema(SCHEMA.read_text(encoding="utf-8"))
    operations, fragments = load_documents()
    lines = [
        '"""GENERATED by scripts/codegen.py from schema.gql and operations/. Do not edit.',
        "",
        f"schema.gql sha256: {schema_sha}",
        f"operations/ sha256: {ops_sha}",
        '"""',
        "",
        "from crowdypy._operation import Operation",
        "",
    ]
    names: list[str] = []
    for rel, op in sorted(operations, key=lambda item: item[1].name.value if item[1].name else ""):
        document = isolate(op, fragments)
        errors = validate(schema, document)
        if errors:
            details = "; ".join(e.message for e in errors[:3])
            raise SystemExit(
                f"codegen: {op.name.value if op.name else '?'} ({rel}) is invalid: {details}"
            )
        assert op.name is not None
        # The response KEY of each root selection: its alias when it has one.
        roots = tuple(
            (selection.alias or selection.name).value  # type: ignore[attr-defined]
            for selection in op.selection_set.selections
            if hasattr(selection, "name")
        )
        const = screaming(op.name.value)
        names.append(const)
        lines += [
            "",
            f"# {rel}",
            f"{const} = Operation(",
            f"    name={op.name.value!r},",
            f"    kind={op.operation.value!r},",
            f"    root_fields={roots!r},",
            f"    document={print_ast(document)!r},",
            ")",
        ]
    lines += [
        "",
        "#: Every generated operation, by GraphQL operation name.",
        "OPERATIONS: dict[str, Operation] = {op.name: op for op in (",
        *(f"    {n}," for n in names),
        ")}",
        "",
    ]
    return "\n".join(lines)


def _py_type(gql_type: object, schema_types: dict[str, object], wrap_optional: bool) -> str:
    if isinstance(gql_type, GraphQLNonNull):
        return _py_type(gql_type.of_type, schema_types, wrap_optional=False)
    if isinstance(gql_type, GraphQLList):
        inner = _py_type(gql_type.of_type, schema_types, wrap_optional=True)
        base = f"list[{inner}]"
    elif isinstance(gql_type, GraphQLScalarType):
        base = SCALARS.get(gql_type.name, "Any")
    elif isinstance(gql_type, (GraphQLEnumType, GraphQLInputObjectType)):
        base = gql_type.name
    else:  # pragma: no cover - output types never appear in inputs
        base = "Any"
    return f"{base} | None" if wrap_optional else base


def render_enums(schema_sha: str) -> str:
    schema = build_schema(SCHEMA.read_text(encoding="utf-8"))
    lines = [
        '"""GENERATED by scripts/codegen.py from schema.gql. Do not edit.',
        "",
        f"schema.gql sha256: {schema_sha}",
        '"""',
        "",
        "from enum import StrEnum",
        "",
    ]
    names: list[str] = []
    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if not isinstance(gql_type, GraphQLEnumType) or name.startswith("__"):
            continue
        names.append(name)
        lines += ["", f"class {name}(StrEnum):"]
        if gql_type.description:
            lines.append(f"    {gql_type.description.strip().splitlines()[0]!r}")
        for value in gql_type.values:
            lines.append(f"    {py_identifier(value)} = {value!r}")
        if not gql_type.values:
            lines.append("    pass")
        lines.append("")
    lines += ["", "__all__ = [", *(f"    {n!r}," for n in names), "]", ""]
    return "\n".join(lines)


def render_inputs(schema_sha: str) -> str:
    schema = build_schema(SCHEMA.read_text(encoding="utf-8"))
    enum_names = sorted(
        n
        for n, t in schema.type_map.items()
        if isinstance(t, GraphQLEnumType) and not n.startswith("__")
    )
    lines = [
        '"""GENERATED by scripts/codegen.py from schema.gql. Do not edit.',
        "",
        "Every GraphQL input object as a msgspec Struct. Attributes are snake_case and encode",
        "under their GraphQL names; an attribute left at UNSET is omitted from the request,",
        "which is how the API tells 'not provided' from an explicit null.",
        "",
        f"schema.gql sha256: {schema_sha}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "import msgspec",
        "from msgspec import UNSET, UnsetType",
        "",
        f"from crowdypy._generated.enums import {', '.join(enum_names)}",
        "",
    ]
    names: list[str] = []
    for name in sorted(schema.type_map):
        gql_type = schema.type_map[name]
        if not isinstance(gql_type, GraphQLInputObjectType) or name.startswith("__"):
            continue
        names.append(name)
        fields = list(gql_type.fields.items())
        renames = {}
        body: list[str] = []
        for field_name, field in fields:
            attr = py_identifier(snake(field_name))
            if attr != field_name:
                renames[attr] = field_name
            required = isinstance(field.type, GraphQLNonNull) and field.default_value is Undefined
            annotation = _py_type(field.type, schema.type_map, wrap_optional=True)
            if required:
                body.append(f"    {attr}: {annotation}")
            else:
                body.append(f"    {attr}: {annotation} | UnsetType = UNSET")
        rename = f", rename={renames!r}" if renames else ""
        lines += ["", f"class {name}(msgspec.Struct, kw_only=True, omit_defaults=True{rename}):"]
        if gql_type.description:
            lines.append(f"    {gql_type.description.strip().splitlines()[0]!r}")
        lines += body or ["    pass"]
        lines.append("")
    lines += ["", "__all__ = [", *(f"    {n!r}," for n in names), "]", ""]
    return "\n".join(lines)


def outputs() -> dict[Path, str]:
    schema_sha = hashlib.sha256(SCHEMA.read_bytes()).hexdigest()
    ops_files = {
        p.relative_to(OPERATIONS).as_posix(): p.read_bytes()
        for p in sorted(OPERATIONS.rglob("*.graphql"))
    }
    ops_sha = tree_sha256(ops_files)
    return {
        OUT
        / "__init__.py": '"""Modules generated from schema.gql and operations/ by scripts/codegen.py."""\n',
        OUT / "operations.py": render_operations(schema_sha, ops_sha),
        OUT / "enums.py": render_enums(schema_sha),
        OUT / "inputs.py": render_inputs(schema_sha),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale: list[str] = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"codegen: wrote {path.relative_to(ROOT).as_posix()}")
    if stale:
        print(
            "codegen: generated modules are stale or hand-edited: "
            + ", ".join(stale)
            + "\nRun `python scripts/codegen.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("codegen: OK -- generated modules match schema.gql and operations/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
