#!/usr/bin/env python3
"""Generate the blocking client (src/crowdypy/_sync/) from the async source.

    python scripts/unasync.py          # write
    python scripts/unasync.py --check  # regenerate in memory; refuse drift

The async modules are the source of truth: ``graphql.py``, ``client.py``,
``rediscover.py``, ``grid_scope.py``, ``world.py``, ``stores.py``, ``domains/`` and
``kit/``. A token-level rewrite (formatting is preserved) drops ``async``/``await``, maps
the async names to their blocking twins and points imports of those modules at
``crowdypy._sync``. ``asyncio.sleep`` becomes ``time.sleep``; any other use of asyncio in a
source module is refused, because it would have no blocking equivalent.
"""

from __future__ import annotations

import argparse
import ast
import io
import re
import sys
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "crowdypy"
OUT = PKG / "_sync"

SOURCES = [
    "graphql.py",
    "client.py",
    "rediscover.py",
    "grid_scope.py",
    "world.py",
    "stores.py",
    "domains",
    "kit",
]
SYNC_MODULES = {
    "graphql",
    "client",
    "rediscover",
    "grid_scope",
    "world",
    "stores",
    "domains",
    "kit",
}

NAMES = {
    "AsyncCrowdyClient": "CrowdyClient",
    "AsyncGraphQLClient": "GraphQLClient",
    "AsyncSingleFlight": "SingleFlight",
    "AsyncReplicationConnection": "ReplicationConnection",
    "AsyncExecConnection": "ExecConnection",
    "run_soon": "run_now",
    "AsyncClient": "Client",
    "aclose": "close",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    "__aiter__": "__iter__",
    "__anext__": "__next__",
    "AsyncIterator": "Iterator",
    "AsyncIterable": "Iterable",
    "AsyncGenerator": "Generator",
    "StopAsyncIteration": "StopIteration",
    "asyncio": "time",
}
_PROSE = [
    (re.compile(r"\bawait\s+"), ""),
    (re.compile(r"\basync\s+(def|with|for)\b"), r"\1"),
    *((re.compile(rf"\b{re.escape(a)}\b"), b) for a, b in NAMES.items() if a != "asyncio"),
]


def _offsets(source: str) -> list[int]:
    starts = [0]
    for line in source.splitlines(keepends=True):
        starts.append(starts[-1] + len(line))
    return starts


def transform(source: str, rel: str) -> str:
    starts = _offsets(source)
    pos = lambda point: starts[point[0] - 1] + point[1]  # noqa: E731
    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    edits: list[tuple[int, int, str]] = []
    for i, tok in enumerate(tokens):
        nxt = tokens[i + 1] if i + 1 < len(tokens) else None
        if tok.type == tokenize.NAME and tok.string == "await":
            end = pos(nxt.start) if nxt and nxt.start[0] == tok.end[0] else pos(tok.end)
            edits.append((pos(tok.start), end, ""))
        elif (
            tok.type == tokenize.NAME
            and tok.string == "async"
            and nxt
            and nxt.string in ("def", "with", "for")
        ):
            edits.append((pos(tok.start), pos(nxt.start), ""))
        elif tok.type == tokenize.NAME and tok.string == "asyncio":
            after = tokens[i + 2] if i + 2 < len(tokens) else None
            is_import = i > 0 and tokens[i - 1].string == "import"
            if not is_import and not (
                nxt and nxt.string == "." and after and after.string == "sleep"
            ):
                raise SystemExit(f"unasync: {rel}:{tok.start[0]} uses asyncio beyond asyncio.sleep")
            edits.append((pos(tok.start), pos(tok.end), "time"))
        elif tok.type == tokenize.NAME and tok.string in NAMES:
            edits.append((pos(tok.start), pos(tok.end), NAMES[tok.string]))
        elif (
            tok.type == tokenize.NAME
            and tok.string == "crowdypy"
            and nxt
            and nxt.string == "."
            and i + 2 < len(tokens)
            and tokens[i + 2].string in SYNC_MODULES
        ):
            module = tokens[i + 2]
            edits.append((pos(module.start), pos(module.start), "_sync."))
        elif tok.type in (tokenize.STRING, tokenize.COMMENT):
            text = tok.string
            for pattern, replacement in _PROSE:
                text = pattern.sub(replacement, text)
            if text != tok.string:
                edits.append((pos(tok.start), pos(tok.end), text))
    out = source
    for start, end, replacement in sorted(edits, reverse=True):
        out = out[:start] + replacement + out[end:]
    out = _share_plain_classes(source, out, rel)
    header = f"# GENERATED by scripts/unasync.py from src/crowdypy/{rel}. Do not edit.\n"
    return header + out


def _share_plain_classes(source: str, out: str, rel: str) -> str:
    """Import, rather than redefine, every class the blocking client can use as it is.

    A class with no async code (an error, a result struct, a store with only blocking
    methods) must be ONE class in both clients, or ``except crowdypy.SomeError`` misses what
    the blocking client raises. A class is shared when its definition holds nothing async,
    no async-only name and nothing imported from a module this script rewrites. The token
    rewrite keeps every line where it was, so the source's line numbers locate it in ``out``.
    """
    tree = ast.parse(source)
    rewritten: set[str] = set(NAMES)
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            parts = node.module.split(".")
            if parts[0] == "crowdypy" and len(parts) > 1 and parts[1] in SYNC_MODULES:
                rewritten.update(alias.asname or alias.name for alias in node.names)
    shared: list[ast.ClassDef] = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        plain = True
        for inner in ast.walk(node):
            if (
                isinstance(inner, (ast.AsyncFunctionDef, ast.Await, ast.AsyncFor, ast.AsyncWith))
                or (isinstance(inner, ast.Name) and inner.id in rewritten)
                or (isinstance(inner, ast.Attribute) and inner.attr in NAMES)
            ):
                plain = False
            if not plain:
                break
        if plain:
            shared.append(node)
    # A class that names another class of this module that stays two (an API class in an
    # annotation, a base) would hand the blocking client the async one: keep it two as well.
    local = {n.name for n in tree.body if isinstance(n, ast.ClassDef)}
    while True:
        keep = {n.name for n in shared}
        two = local - keep
        narrowed = [
            n
            for n in shared
            if not any(isinstance(i, ast.Name) and i.id in two for i in ast.walk(n))
            and not any(isinstance(i, ast.Constant) and i.value in two for i in ast.walk(n))
        ]
        if len(narrowed) == len(shared):
            break
        shared = narrowed
    if not shared:
        return out
    lines = out.split("\n")
    for node in sorted(shared, key=lambda n: n.lineno, reverse=True):
        first = min([node.lineno, *(d.lineno for d in node.decorator_list)])
        del lines[first - 1 : node.end_lineno]
    imports = [n for n in tree.body if isinstance(n, (ast.Import, ast.ImportFrom))]
    at = max(n.end_lineno or n.lineno for n in imports) if imports else 0
    module = "crowdypy." + rel.removesuffix(".py").replace("/", ".").removesuffix(".__init__")
    names = ", ".join(sorted(node.name for node in shared))
    lines.insert(at, f"from {module} import {names}  # one class in both clients")
    return "\n".join(lines)


def outputs() -> dict[Path, str]:
    result: dict[Path, str] = {
        OUT
        / "__init__.py": '"""The blocking client, generated from the async source by scripts/unasync.py."""\n',
    }
    for entry in SOURCES:
        path = PKG / entry
        files = sorted(path.rglob("*.py")) if path.is_dir() else [path]
        for file in files:
            rel = file.relative_to(PKG).as_posix()
            result[OUT / rel] = transform(file.read_text(encoding="utf-8"), rel)
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = outputs()
    existing = {p for p in OUT.rglob("*.py")} if OUT.exists() else set()
    stale = sorted(p.relative_to(ROOT).as_posix() for p in existing - expected.keys())
    changed: list[str] = []
    for path, text in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        changed.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if not args.check:
        for rel in stale:
            (ROOT / rel).unlink()
        print(f"unasync: {len(changed)} file(s) written, {len(stale)} stale file(s) removed")
        return 0
    if changed or stale:
        print(
            "unasync: the blocking client is stale: "
            + ", ".join(changed + [f"{s} (no source)" for s in stale])
            + "\nRun `python scripts/unasync.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(f"unasync: OK -- {len(expected)} generated module(s) match their async source")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
