"""Player-host observation: the typed contract a game implements so tooling can read the
player it controls and its surroundings, the schemas that validate it, and the agent error
vocabulary (CrowdyJS's ``player-host``)."""

from crowdypy.player_host.agent_errors import (
    CROWDY_AGENT_ERROR_CODES,
    AgentErrorV1,
    CrowdyAgentError,
    CrowdyAgentErrorCode,
    CrowdyAgentOutcomeUnknownError,
    to_agent_error,
)
from crowdypy.player_host.agent_types import (
    CrowdyAgentApprovalPolicy,
    CrowdyAgentLeaseV1,
    CrowdyAgentPreemptionReason,
    CrowdyAgentToolRisk,
)
from crowdypy.player_host.json_schema import (
    FORBIDDEN_AGENT_AUTHORITY_FIELDS,
    JsonSchema,
    assert_bounded_json_schema,
    canonical_json,
    deep_freeze,
    digest_canonical_json,
    is_decimal_string,
    sha256_digest,
    validate_json_schema_value,
)
from crowdypy.player_host.schemas import (
    GAME_COMMAND_RESULT_SCHEMA_V1,
    GAME_COMMAND_SCHEMA_V1,
    GAME_COMMAND_SCHEMAS_V1,
    GAME_OBSERVATION_SCHEMA_V1,
    OBSERVE_REQUEST_SCHEMA_V1,
    PLAYER_HOST_CAPABILITIES_SCHEMA_V1,
)
from crowdypy.player_host.types import (
    GameCommandResultV1,
    GameCommandV1,
    GameObservationActorV1,
    GameObservationInventoryV1,
    GameObservationV1,
    ObserveRequestV1,
    PlayerHostAdapterV1,
    PlayerHostCapabilitiesV1,
    PlayerHostCommandCapabilityV1,
    PlayerHostCommandKind,
    PlayerHostLeaseScope,
    PlayerHostLookV1,
    PlayerHostVector3V1,
    ValidatedGateV1,
)

__all__ = [
    "CROWDY_AGENT_ERROR_CODES",
    "FORBIDDEN_AGENT_AUTHORITY_FIELDS",
    "GAME_COMMAND_RESULT_SCHEMA_V1",
    "GAME_COMMAND_SCHEMAS_V1",
    "GAME_COMMAND_SCHEMA_V1",
    "GAME_OBSERVATION_SCHEMA_V1",
    "OBSERVE_REQUEST_SCHEMA_V1",
    "PLAYER_HOST_CAPABILITIES_SCHEMA_V1",
    "AgentErrorV1",
    "CrowdyAgentApprovalPolicy",
    "CrowdyAgentError",
    "CrowdyAgentErrorCode",
    "CrowdyAgentLeaseV1",
    "CrowdyAgentOutcomeUnknownError",
    "CrowdyAgentPreemptionReason",
    "CrowdyAgentToolRisk",
    "GameCommandResultV1",
    "GameCommandV1",
    "GameObservationActorV1",
    "GameObservationInventoryV1",
    "GameObservationV1",
    "JsonSchema",
    "ObserveRequestV1",
    "PlayerHostAdapterV1",
    "PlayerHostCapabilitiesV1",
    "PlayerHostCommandCapabilityV1",
    "PlayerHostCommandKind",
    "PlayerHostLeaseScope",
    "PlayerHostLookV1",
    "PlayerHostVector3V1",
    "ValidatedGateV1",
    "assert_bounded_json_schema",
    "canonical_json",
    "deep_freeze",
    "digest_canonical_json",
    "is_decimal_string",
    "sha256_digest",
    "to_agent_error",
    "validate_json_schema_value",
]
